# Required nodes from outside the framework:
# net_emissions
# Required dimensions from outside the framework:
# building_energy_class
# heating_type
# ghg
# scope
# Required parameters from outside the framework:
# population_growth_rate

emission_sectors:

- id: building_emissions
  name: Building emissions
  description: 'This module (all nodes upstream) is based on the excel sheets 3.0 - 3.4 Building & heat levers.'
  part_of: net_emissions

nodes:

# * = data is in the city request dataset
# Model inputs: 176* 519 257* 254* 532 544 545 272* 273* 278 290 296..299* 302..305* 319..322* 586
# 3.4 heat generation: (coming from model inputs) 19 25 248 259

- id: existing_building_stock
  name: Existing building stock
  description: 'Data sources:<ul><li>Model inputs & assumptions, F250. Size of building stock. 
    </li><li>Model inputs & assumptions, F519. Rate of demolition and new construction.</li><li>Model inputs & assumptions, F257. Retrofitted area %.</li></ul>
    Calculations: The logic is that the floor area per inhabitant stays constant. Amount of construction is a fixed fraction of existing building stock and the difference between building stock increase and construction is assumed to be demolished. So, logically, construction must be greater than or equal to population growth.'
  type: gpc.DatasetNode
  quantity: floor_area
  unit: km**2
  input_dimensions: [building_energy_class]
  output_dimensions: [building_energy_class]
  input_datasets:
  - id: nzc/defaults/buildings
    forecast_from: 2023
  params:
  - id: gpc_sector
    value: size of building stock

- id: building_stock  # FIXME Calculate the demolition
  name: Building stock
  description: Existing building stock minus demolition and new construction.
  type: simple.AdditiveNode
  quantity: floor_area
  unit: km**2
  input_dimensions: [building_energy_class]
  output_dimensions: [building_energy_class]
  input_nodes:
  - id: existing_building_stock
    to_dimensions:
    - id: building_energy_class

- id: energy_use_intensity
  name: Energy use intensity
  description: Data comes from user for minimum building standard (38 comes from Madrid as a placeholder)
  type: gpc.DatasetNode
  quantity: energy_factor
  unit: kWh/m**2/a
  input_dimensions: [building_energy_class]
  output_dimensions: [building_energy_class]
  input_datasets:
  - id: nzc/defaults/buildings
    forecast_from: 2023
  params:
  - id: gpc_sector
    value: energy use intensity

- id: building_heating_type_share
  name: Building heating type share
  description: Assumes 1 % district and 99 % local heating. Data comes from the user.
  type: gpc.DatasetNode
  quantity: fraction
  unit: dimensionless
  input_dimensions: [heating_type, scope]
  output_dimensions: [heating_type, scope]
  input_datasets:
  - id: nzc/defaults/buildings
    forecast_from: 2023
  params:
  - id: gpc_sector
    value: building heating shares

- id: building_energy_use
  name: Building energy use
  description: 'For the frozen scenario, heat energy is relative to population growth.'
  type: simple.MultiplicativeNode
  quantity: energy
  unit: GWh/a
  input_dimensions: [heating_type, building_energy_class, scope]
  output_dimensions: [heating_type, building_energy_class, scope]
  input_nodes:
  - id: building_stock
    to_dimensions:
    - id: building_energy_class
  - id: energy_use_intensity
    to_dimensions:
    - id: building_energy_class
  - id: building_heating_type_share
    to_dimensions:
    - id: heating_type
    - id: scope

- id: heating_emission_factor
  name: Heating emission factor
  description: Emission factor for building heating
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: g/kWh
  input_dimensions: [pollutant, heating_type]
  output_dimensions: [pollutant, heating_type]
  input_datasets:
  - id: nzc/defaults/buildings
    forecast_from: 2023
  params:
  - id: gpc_sector
    value: heat emission factor

- id: building_heating_emissions
  name: Building heating emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [heating_type, ghg, scope]
  output_dimensions: [heating_type, ghg, scope]
  input_nodes:
  - id: building_energy_use
    from_dimensions:
    - id: building_energy_class
      flatten: true
    to_dimensions:
    - id: heating_type
    - id: scope
  - id: heating_emission_factor
    from_dimensions:
    - id: pollutant
      categories: [co2]
      flatten: true
    to_dimensions:
    - id: heating_type
    - id: ghg
      categories: [co2e]
  output_nodes:
  - id: building_emissions
    from_dimensions:
    - id: heating_type
      flatten: true

#actions:

#- id: renovation_rate
#  name: Renovation rate
#  description: 'Default 1 %, BPIE (2011) - "Europe's buildings under the microscope". http://bpie.eu/wp-content/uploads/2015/10/HR_EU_B_under_microscope_study.pdf'
#  type: shift.ShiftAction
#  quantity: fraction
#  unit: '%'
#  params:
#  - id: shift
#    unit: '%'
#    values:
#    - year: 2023
#      value: 1
