emission_sectors:
- id: building_heating_emissions
  name: Rakennusten lämmityksen päästöt
  part_of: net_emissions
- id: oil_heating_emissions
  name: Öljylämmityksen päästöt
  part_of: building_heating_emissions
- id: direct_electric_heating_emissions
  name: Sähkölämmityksen päästöt
  part_of: building_heating_emissions
- id: geothermal_heating_emissions
  name: Maalämmön päästöt
  part_of: building_heating_emissions
- id: consumer_electricity_emissions
  name: Kulutussähkön päästöt
  part_of: net_emissions
- id: transport_emissions
  name: Liikenteen päästöt
  part_of: net_emissions
- id: road_transport_emissions
  name: Tieliikenteen päästöt
  part_of: transport_emissions
- id: rail_transport_emissions
  name: Raideliikenteen päästöt
  part_of: transport_emissions
- id: water_transport_emissions
  name: Laivaliikenteen päästöt
  part_of: transport_emissions
- id: industry_machinery_emissions
  name: Teollisuuden ja työkoneiden päästöt
  part_of: net_emissions
- id: waste_treatment_emissions
  name: Jätteiden käsittelyn päästöt
  part_of: net_emissions
- id: waste_landfill_emissions
  name: Kaatopaikkojen päästöt
  part_of: waste_treatment_emissions
- id: biowaste_composting_emissions
  name: Biojätteen kompostoinnin päästöt
  part_of: waste_treatment_emissions
- id: waste_water_treatment_emissions
  name: Jäteveden käsittelyn päästöt
  part_of: waste_treatment_emissions
- id: sludge_composting_emissions
  name: Jätevesilietteen kompostoinnin päästöt
  part_of: waste_treatment_emissions
- id: agriculture_emissions
  name: Maatalouden päästöt
  part_of: net_emissions
nodes:
- id: district_heating_energy
  name: Kaukolämmön lämmönkulutus
  params:
    sector: Lämmitys|Kaukolämpö|Kaukolämpö
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: district_heating_emissions
  name: Kaukolämmön päästöt
  output_nodes: [building_heating_emissions]
  input_nodes: [district_heating_emission_factor, district_heating_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: oil_heating_residence_energy
  name: Öljylämmityksen lämmönkulutus (Asuminen)
  params:
    sector: Lämmitys|Öljylämmitys|Öljylämmitys|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: oil_heating_residence_emissions
  name: Öljylämmityksen päästöt (Asuminen)
  output_nodes: [oil_heating_emissions]
  input_nodes: [oil_heating_emission_factor, oil_heating_residence_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: oil_heating_services_energy
  name: Öljylämmityksen lämmönkulutus (Palvelut)
  params:
    sector: Lämmitys|Öljylämmitys|Öljylämmitys|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: oil_heating_services_emissions
  name: Öljylämmityksen päästöt (Palvelut)
  output_nodes: [oil_heating_emissions]
  input_nodes: [oil_heating_emission_factor, oil_heating_services_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: oil_heating_industry_energy
  name: Öljylämmityksen lämmönkulutus (Teollisuus)
  params:
    sector: Lämmitys|Öljylämmitys|Öljylämmitys|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: oil_heating_industry_emissions
  name: Öljylämmityksen päästöt (Teollisuus)
  output_nodes: [oil_heating_emissions]
  input_nodes: [oil_heating_emission_factor, oil_heating_industry_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: direct_electric_heating_residence_energy
  name: Sähkölämmityksen sähkönkulutus (Asuminen)
  params:
    sector: Lämmitys|Sähkölämmitys|Sähkölämmitys|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: direct_electric_heating_residence_emissions
  name: Sähkölämmityksen päästöt (Asuminen)
  output_nodes: [direct_electric_heating_emissions]
  input_nodes: [electric_heating_emission_factor, direct_electric_heating_residence_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: direct_electric_heating_services_energy
  name: Sähkölämmityksen sähkönkulutus (Palvelut)
  params:
    sector: Lämmitys|Sähkölämmitys|Sähkölämmitys|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: direct_electric_heating_services_emissions
  name: Sähkölämmityksen päästöt (Palvelut)
  output_nodes: [direct_electric_heating_emissions]
  input_nodes: [electric_heating_emission_factor, direct_electric_heating_services_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: direct_electric_heating_industry_energy
  name: Sähkölämmityksen sähkönkulutus (Teollisuus)
  params:
    sector: Lämmitys|Sähkölämmitys|Sähkölämmitys|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: direct_electric_heating_industry_emissions
  name: Sähkölämmityksen päästöt (Teollisuus)
  output_nodes: [direct_electric_heating_emissions]
  input_nodes: [electric_heating_emission_factor, direct_electric_heating_industry_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: geothermal_heating_residence_energy
  name: Maalämmön sähkönkulutus (Asuminen)
  params:
    sector: Lämmitys|Maalämpö|Maalämpö|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: geothermal_heating_residence_emissions
  name: Maalämmön päästöt (Asuminen)
  output_nodes: [geothermal_heating_emissions]
  input_nodes: [electric_heating_emission_factor, geothermal_heating_residence_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: geothermal_heating_services_energy
  name: Maalämmön sähkönkulutus (Palvelut)
  params:
    sector: Lämmitys|Maalämpö|Maalämpö|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: geothermal_heating_services_emissions
  name: Maalämmön päästöt (Palvelut)
  output_nodes: [geothermal_heating_emissions]
  input_nodes: [electric_heating_emission_factor, geothermal_heating_services_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: geothermal_heating_industry_energy
  name: Maalämmön sähkönkulutus (Teollisuus)
  params:
    sector: Lämmitys|Maalämpö|Maalämpö|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: geothermal_heating_industry_emissions
  name: Maalämmön päästöt (Teollisuus)
  output_nodes: [geothermal_heating_emissions]
  input_nodes: [electric_heating_emission_factor, geothermal_heating_industry_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: consumer_electricity_residence_energy
  name: Kulutussähkön sähkönkulutus (Asuminen)
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: consumer_electricity_residence_emissions
  name: Kulutussähkön päästöt (Asuminen)
  output_nodes: [consumer_electricity_emissions]
  input_nodes: [electricity_production_emission_factor, consumer_electricity_residence_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: consumer_electricity_services_energy
  name: Kulutussähkön sähkönkulutus (Palvelut)
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: consumer_electricity_services_emissions
  name: Kulutussähkön päästöt (Palvelut)
  output_nodes: [consumer_electricity_emissions]
  input_nodes: [electricity_production_emission_factor, consumer_electricity_services_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: consumer_electricity_industry_energy
  name: Kulutussähkön sähkönkulutus (Teollisuus)
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: consumer_electricity_industry_emissions
  name: Kulutussähkön päästöt (Teollisuus)
  output_nodes: [consumer_electricity_emissions]
  input_nodes: [electricity_production_emission_factor, consumer_electricity_industry_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: car_emissions
  name: Henkilöautot päästöt
  output_nodes: [road_transport_emissions]
  params:
    sector: Liikenne|Tieliikenne|Henkilöautot|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: motorbike_emissions
  name: Moottoripyörät päästöt
  output_nodes: [road_transport_emissions]
  params:
    sector: Liikenne|Tieliikenne|Moottoripyörät|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: van_emissions
  name: Pakettiautot päästöt
  output_nodes: [road_transport_emissions]
  params:
    sector: Liikenne|Tieliikenne|Pakettiautot|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: truck_emissions
  name: Kuorma-autot päästöt
  output_nodes: [road_transport_emissions]
  params:
    sector: Liikenne|Tieliikenne|Kuorma-autot|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: bus_emissions
  name: Linja-autot päästöt
  output_nodes: [road_transport_emissions]
  params:
    sector: Liikenne|Tieliikenne|Linja-autot|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: local_train_energy
  name: Lähijunien sähkönkulutus
  params:
    sector: Liikenne|Raideliikenne|Lähijunat|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: local_train_emissions
  name: Lähijunien päästöt
  output_nodes: [rail_transport_emissions]
  input_nodes: [electricity_production_emission_factor, local_train_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: metro_energy
  name: Metroliikenteen sähkönkulutus
  params:
    sector: Liikenne|Raideliikenne|Metrot|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: metro_emissions
  name: Metroliikenteen päästöt
  output_nodes: [rail_transport_emissions]
  input_nodes: [electricity_production_emission_factor, metro_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: tram_energy
  name: Raitiovaunujen sähkönkulutus
  params:
    sector: Liikenne|Raideliikenne|Raitiovaunut|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
- id: tram_emissions
  name: Raitiovaunujen päästöt
  output_nodes: [rail_transport_emissions]
  input_nodes: [electricity_production_emission_factor, tram_energy]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: yacht_emissions
  name: Huviveneiden päästöt
  output_nodes: [water_transport_emissions]
  params:
    sector: Liikenne|Laivaliikenne|Huviveneet|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: work_boat_emissions
  name: Ammattiveneiden päästöt
  output_nodes: [water_transport_emissions]
  params:
    sector: Liikenne|Laivaliikenne|Ammattiveneet|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: passenger_ship_emissions
  name: Matkustajalaivojen päästöt
  output_nodes: [water_transport_emissions]
  params:
    sector: Liikenne|Laivaliikenne|Matkustajalaivat|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: freight_ship_emissions
  name: Rahtilaivojen päästöt
  output_nodes: [water_transport_emissions]
  params:
    sector: Liikenne|Laivaliikenne|Rahtilaivat|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: machinery_emissions
  name: Työkoneiden päästöt
  output_nodes: [industry_machinery_emissions]
  params:
    sector: Teollisuus ja työkoneet|Työkoneet|Työkoneet|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: industry_fuel_emissions
  name: Teollisuuden polttoaineiden päästöt
  output_nodes: [industry_machinery_emissions]
  params:
    sector: Teollisuus ja työkoneet|Polttoaineet|Polttoaineet|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: industrial_processes_emissions
  name: Teollisuusprosessien päästöt
  output_nodes: [industry_machinery_emissions]
  params:
    sector: Teollisuus ja työkoneet|Prosessit|Prosessit|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: waste_landfill_residence_emissions
  name: Kaatopaikkojen päästöt (Asuminen)
  output_nodes: [waste_landfill_emissions]
  params:
    sector: Jätteiden käsittely|Kaatopaikka|Kaatopaikka|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: waste_landfill_services_emissions
  name: Kaatopaikkojen päästöt (Palvelut)
  output_nodes: [waste_landfill_emissions]
  params:
    sector: Jätteiden käsittely|Kaatopaikka|Kaatopaikka|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: waste_landfill_industry_emissions
  name: Kaatopaikkojen päästöt (Teollisuus)
  output_nodes: [waste_landfill_emissions]
  params:
    sector: Jätteiden käsittely|Kaatopaikka|Kaatopaikka|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: biowaste_composting_residence_emissions
  name: Biojätteen kompostoinnin päästöt (Asuminen)
  output_nodes: [biowaste_composting_emissions]
  params:
    sector: Jätteiden käsittely|Biojätteen kompostointi|Biojätteen kompostointi|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: biowaste_composting_services_emissions
  name: Biojätteen kompostoinnin päästöt (Palvelut)
  output_nodes: [biowaste_composting_emissions]
  params:
    sector: Jätteiden käsittely|Biojätteen kompostointi|Biojätteen kompostointi|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: biowaste_composting_industry_emissions
  name: Biojätteen kompostoinnin päästöt (Teollisuus)
  output_nodes: [biowaste_composting_emissions]
  params:
    sector: Jätteiden käsittely|Biojätteen kompostointi|Biojätteen kompostointi|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: waste_water_treatment_residence_emissions
  name: Jäteveden käsittelyn päästöt (Asuminen)
  output_nodes: [waste_water_treatment_emissions]
  params:
    sector: Jätteiden käsittely|Jäteveden käsittely|Jäteveden käsittely|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: waste_water_treatment_services_emissions
  name: Jäteveden käsittelyn päästöt (Palvelut)
  output_nodes: [waste_water_treatment_emissions]
  params:
    sector: Jätteiden käsittely|Jäteveden käsittely|Jäteveden käsittely|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: waste_water_treatment_industry_emissions
  name: Jäteveden käsittelyn päästöt (Teollisuus)
  output_nodes: [waste_water_treatment_emissions]
  params:
    sector: Jätteiden käsittely|Jäteveden käsittely|Jäteveden käsittely|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: sludge_composting_residence_emissions
  name: Jätevesilietteen kompostoinnin päästöt (Asuminen)
  output_nodes: [sludge_composting_emissions]
  params:
    sector: Jätteiden käsittely|Jätevesilietteen kompostointi|Jätevesilietteen kompostointi|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: sludge_composting_services_emissions
  name: Jätevesilietteen kompostoinnin päästöt (Palvelut)
  output_nodes: [sludge_composting_emissions]
  params:
    sector: Jätteiden käsittely|Jätevesilietteen kompostointi|Jätevesilietteen kompostointi|Palvelut
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: sludge_composting_industry_emissions
  name: Jätevesilietteen kompostoinnin päästöt (Teollisuus)
  output_nodes: [sludge_composting_emissions]
  params:
    sector: Jätteiden käsittely|Jätevesilietteen kompostointi|Jätevesilietteen kompostointi|Teollisuus
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: agricultural_field_emissions
  name: Peltojen päästöt
  output_nodes: [agriculture_emissions]
  params:
    sector: Maatalous|Pellot|Pellot|Maatalous
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: agricultural_cattle_emissions
  name: Kotieläimien päästöt
  output_nodes: [agriculture_emissions]
  params:
    sector: Maatalous|Kotieläimet|Kotieläimet|Maatalous
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions
- id: district_heating_emission_factor
  name: Kaukolämmön päästökerroin
  name_en: District heating emission factor
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Lämmitys|Kaukolämpö|Kaukolämpö|Asuminen
- id: oil_heating_emission_factor
  name: Öljylämmityksen päästökerroin
  name_en: Oil heating emission factor
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Lämmitys|Öljylämmitys|Öljylämmitys|Asuminen
- id: electricity_production_emission_factor
  name: Kansallisen sähköntuotannon päästökerroin
  name_en: National electricity production emission factor
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|Asuminen
- id: electric_heating_emission_factor
  name: Lämmityssähkön päästökerroin
  name_en: Electric heating emission factor
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Lämmitys|Sähkölämmitys|Sähkölämmitys|Asuminen
