nodes:
- id: motorised_transport_need
  name: Motorised transport need
  type: simple.RelativeNode
  quantity: mileage
  unit: Mvkm/a
  historical_values: [[2019, 100]]

actions:
- id: reduce_motorised_transport_need
  name: Reduce motorised transport need
  type: simple.LinearCumulativeAdditiveAction
  quantity: fraction
  unit: '%'
  group: transport
  forecast_values: [[2024, 0]]
  params:
  - id: target_year_level
    value: -35
    unit: '%'
    is_visible: true
    is_customizable: true
  output_nodes:
  - id: motorised_transport_need
    tags: [non_additive]
