version: '3.8'
services:
  db:
    # Set DB_IMAGE to specify the image name and tag for docker-compose push
    image: ${DB_IMAGE-kausal-paths-postgres}
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=paths
      - POSTGRES_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: ${REDIS_IMAGE-redis:6.0-alpine}
    restart: always

  app:
    # Set APP_IMAGE to specify the image name and tag for docker-compose push
    image: ${APP_IMAGE-kausal-paths}
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - STATIC_ROOT=/srv/static
        - MEDIA_ROOT=/srv/media
        - EXTRA_PYPI_INDEX
        - EXTRA_INSTALLED_APPS_VERSIONS
        - EXTRA_INSTALLED_APPS
    restart: always
    volumes:
      - paths_media:/srv/media
      - paths_build_cache:/root/.cache
    environment:
      - DATABASE_URL
      - ENV_FILE
      - REDIS_URL=redis://redis
      - STATIC_ROOT=/srv/static
      - MEDIA_ROOT=/srv/media
      - LC_CTYPE=C.UTF-8
      - DEBUG
      - DEPLOYMENT_TYPE
      - ALLOWED_HOSTS
      - COOKIE_PREFIX
      - INTERNAL_IPS
      - SENTRY_DSN
      - SECRET_KEY
    depends_on:
      - db
      - redis

volumes:
  db_data:
  paths_media:
  paths_build_cache:
