version: '3.2'
services:
  db:
    image: docker.kausal.tech/postgres
    environment:
      - POSTGRES_USER=paths
      - POSTGRES_PASSWORD
      - POSTGRES_PASSWORD_FILE
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  app:
    volumes:
      - paths_media:/srv/media
      - paths_build_cache:/root/.cache
    environment:
      - DATABASE_URL
      - DATABASE_URL_FILE
      - ENV_FILE
      - REDIS_URL=redis://redis
      - STATIC_ROOT=/srv/static
      - MEDIA_ROOT=/srv/media
      - LC_CTYPE=C.UTF-8
      - DEBUG
      - ALLOWED_HOSTS
      - COOKIE_PREFIX
      - INTERNAL_IPS
      - SENTRY_DSN
      - SECRET_KEY
      - SECRET_KEY_FILE
      - EXTRA_INSTALLED_APPS
      - EXTRA_INSTALLED_APPS_URLS
    depends_on:
      - db
      - redis

volumes:
  db_data:
  paths_media:
  paths_build_cache:
