id: espoo
default_language: fi
supported_languages: [en]
framework: hsy
site_url: https://espoo.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: bf422ab63b0b33090925b2a141d7d275687355a1
name: Hiilineutraali Espoo 2030
name_en: Carbon-neutral Espoo 2030
owner: Espoon kaupunki
owner_en: City of Espoo
theme_identifier: espoo-ilmasto
emission_unit: kt/a
target_year: 2030
reference_year: 1990
minimum_historical_year: 2000
params:
- id: municipality_name
  value: Espoo

emission_sectors:
- id: net_emissions
  name: Kokonaispäästöt (scope 2)
  name_en: Net emissions (scope 2)
  target_year_goal: 245

- id: building_heating_emissions
  color: '#ff4f57'

- id: consumer_electricity_emissions
  color: '#0047b6'

- id: transport_emissions
  color: '#014B30'

nodes:
- id: population
  type: finland.Population
  name: Väestö

- id: all_hsy_emissions
  type: finland.hsy.HsyNode
  name: HSY:n päästöinventaario

#- id: electricity_production_emission_factor
#  type: simple.AdditiveNode
#  name: Kansallisen sähköntuotannon päästökerroin
#  unit: g/kWh
#  quantity: emission_factor
#  input_nodes:
#  - consumer_electricity_residence_emission_factor

pages:
- id: home
  name: Hiilineutraali Espoo -päästöskenaario
  path: /
  type: emission
  node: net_emissions
  lead_title: Espoon päästöskenaariot
  lead_title_en: Espoo emission scenarios
  lead_paragraph: Espoon päästöskenaariot visualisoi Espoon kasvihuonekaasupäästöjen
    kehityksen. Voit tarkastella, mistä Espoon kaupungin alueen päästöt syntyvät ja
    kuinka niiden ennustetaan muuttuvan vuoteen 2030 mennessä. Valittavana on peruskehitys-skenaario,
    Hiilineutraali Espoo -tiekartan mukainen skenaario ja skenaario, jota voit itse
    muokata. Hiilineutraaliksi pääseminen edellyttää vielä lisää toimia, ja niiden
    riittävyyttä arvioidaan jatkossa tämän työkalun avulla.

actions:
- id: city_building_heat_optimization
  name: Kaupungin kiinteistöjen lämmityksen optimointi
  name_en: Optimization of heating systems in city-owned buildings
  type: simple.CumulativeAdditiveAction
  quantity: energy
  output_nodes:
  - district_heating_services_energy
  forecast_values: [[2023, -8], [2025, -16], [2026, -4], [2027, -4], [2028, -7],
    [2029, -14], [2030, -6]]
  unit: GWh/a

scenarios:
- id: baseline
  name: Nykykehitys
  name_en: Baseline

- id: default
  default: true
  name: Hiilineutraali Espoo 2030 -tiekartta
  name_en: Carbon-neutral Espoo 2030 roadmap
  all_actions_enabled: true
