id: espoo
default_language: fi
supported_languages: [en]
framework: hsy
site_url: https://espoo.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 61d63424e744b72c6faef2d2c06780a467045b40
name: Hiilineutraali Espoo 2030
name_en: Carbon-neutral Espoo 2030
owner: Espoon kaupunki
owner_en: City of Espoo
theme_identifier: espoo-ilmasto
emission_unit: kt/a
model_end_year: 2035
target_year: 2030
reference_year: 1990
minimum_historical_year: 2000
maximum_historical_year: 2021
params:
- id: municipality_name
  value: Espoo

dimensions:
  - id: building_heat_source
    label: Lämmitystapa
    categories:
      - id: district_heat
        label: Kaukolämpö
      - id: oil
        label: Öljylämmitys
      - id: direct_electric
        label: Sähkölämmitys
      - id: geothermal
        label: Maalämpö
      - id: other
        label: Muu tai tuntematon
        aliases: [Muu]
  - id: building_use
    label: Rakennuksen käyttötarkoitus
    categories:
      - id: residence
        label: Asuminen
      - id: services
        label: Palvelut
      - id: industry
        label: Teollisuus
  - id: vehicle
    label: Ajoneuvo
    categories:
    - id: passenger_cars
      label: Henkilöautot
    - id: motorcycles
      label: Moottoripyörät
    - id: vans
      label: Pakettiautot
    - id: trucks
      label: Kuorma-autot
    - id: buses
      label: Linja-autot
    - id: buses_hsl
      label: Linja-autot, HSL
    - id: buses_other
      label: Linja-autot, muut
    - id: local_trains
      label: Lähijunat
    - id: metro
      label: Metrot
    - id: trams
      label: Raitiovaunut
    - id: leasure_boats
      label: Huviveneet
    - id: professional_boats
      label: Ammattiveneet
    - id: passenger_ships
      label: Matkustajalaivat
    - id: cargo_ships
      label: Rahtilaivat
  - id: transportation_class
    label: Liikennemuoto
    categories:
    - id: road_transportation
      label: Tieliikenne
    - id: rail_tranportation
      label: Raideliikenne
    - id: waterborne_navigation
      label: Laivaliikenne
    - id: aviation
      label: Lentoliikenne

emission_sectors:
- id: net_emissions
  name: Kokonaispäästöt (scope 2)
  name_en: Net emissions (scope 2)
  is_outcome: true
  target_year_goal: 245

- id: building_heating_emissions
  color: '#ff4f57'

- id: consumer_electricity_emissions
  color: '#0047b6'

- id: transport_emissions
  color: '#014B30'

nodes:
- id: population
  type: finland.population.Population
  name: Väestö

- id: all_hsy_emissions
  type: finland.hsy.HsyNode
  name: HSY:n päästöinventaario

- id: building_floor_area_existing
  type: finland.aluesarjat.BuildingStock
  name: Nykyisen rakennuskannan kerrosala

- id: building_floor_area_future
  type: finland.aluesarjat.FutureBuildingStock
  name: Uuden rakennuskannan kerrosala
  input_nodes:
    - population
    - id: building_floor_area_existing
      tags: [existing_floor_area]

- id: building_floor_area_renovated
  type: finland.aluesarjat.BuildingStock
  name: Energiasaneeratun rakennuskannan kerrosala

- id: building_heat_existing_historical
  type: finland.hsy.HsyBuildingHeatConsumption
  name: Nykyisen rakennuskannan lämmönkulutus
  tags: [historical_heat]
  input_nodes: [all_hsy_emissions]

- id: building_heat_existing
  type: finland.aluesarjat.BuildingHeatPredict
  name: Nykyisen rakennuskannan lämmönkulutus
  input_nodes: [building_heat_existing_historical, building_floor_area_existing]
  output_nodes:
    - id: district_heating_energy
      from_dimensions:
        - id: building_heat_source
          categories: [district_heat]
          flatten: true
        - id: building_use
          flatten: true
    - id: oil_heating_energy
      from_dimensions:
        - id: building_heat_source
          categories: [oil]
          flatten: true
        - id: building_use
          flatten: true
    - id: geothermal_heating_energy
      from_dimensions:
        - id: building_heat_source
          categories: [geothermal]
          flatten: true
        - id: building_use
          flatten: true

- id: district_heating_energy
  name: Kaukolämmön lämmönkulutus
  type: simple.AdditiveNode
  unit: GWh/a
  quantity: energy

- id: oil_heating_energy
  name: Öljylämmityksen lämmönkulutus
  type: simple.AdditiveNode
  unit: GWh/a
  quantity: energy

- id: transportation_energy
  name: Tieliikenteen energiankulutus
  type: finland.hsy.HsyDataCollection
  quantity: energy
  unit: GWh/a
  input_nodes: [all_hsy_emissions]
  output_dimensions: [vehicle, transportation_class]
  params:
  - id: sector
    value: Liikenne
  - id: dimension1_column
    value: 3
  - id: dimension2_column
    value: 2
  output_nodes:
  - id: car_traffic_energy
    from_dimensions:
    - id: transportation_class
      categories: [road_transportation]
      flatten: true
    - id: vehicle
      categories: [passenger_cars]
      flatten: true
  - id: bus_traffic_energy
    from_dimensions:
    - id: transportation_class
      categories: [road_transportation]
      flatten: true
    - id: vehicle
      categories: [buses]
      flatten: true
  - id: van_traffic_energy
    from_dimensions:
    - id: transportation_class
      categories: [road_transportation]
      flatten: true
    - id: vehicle
      categories: [vans]
      flatten: true
  - id: truck_traffic_energy
    from_dimensions:
    - id: transportation_class
      categories: [road_transportation]
      flatten: true
    - id: vehicle
      categories: [trucks]
      flatten: true
  - id: motorcycle_traffic_energy
    from_dimensions:
    - id: transportation_class
      categories: [road_transportation]
      flatten: true
    - id: vehicle
      categories: [motorcycles]
      flatten: true
  - id: other_transportation_energy
    from_dimensions:
    - id: transportation_class
      categories: [road_transportation]
      exclude: true

- id: transportation_emissions
  name: Tieliikenteen päästöt
  type: finland.hsy.HsyDataCollection
  quantity: emissions
  unit: kt/a
  input_nodes: [all_hsy_emissions]
  output_dimensions: [vehicle, transportation_class]
  params:
  - id: sector
    value: Liikenne
  - id: dimension1_column
    value: 3
  - id: dimension2_column
    value: 2

- id: transportation_emission_factor
  name: Tieliikenteen päästökerroin
  type: simple.DivisiveNode
  quantity: emission_factor
  unit: g/kWh
  output_dimensions: [vehicle, transportation_class]
  input_nodes:
  - transportation_emissions
  - transportation_energy

- id: car_traffic_energy
  name: Autoliikenteen energiankulutus
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2030, 55.1085987], [2035, 159.4475456]]

- id: bus_traffic_energy
  name: Bussiliikenteen energiankulutus
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2030, 0.70604907], [2035, 0.70604907]]

- id: van_traffic_energy
  name: Pakettiautoliikenteen energiankulutus
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2030, 22.35577851], [2035, 36.11318067]]

- id: truck_traffic_energy
  name: Kuorma-autoliikenteen energiankulutus
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2030, 139.8090131], [2035, 150.6124368]]

- id: motorcycle_traffic_energy
  name: Moottoripyöräliikenteen energiankulutus
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2030, 0], [2035, 0]]

- id: other_transportation_energy
  name: Muun liikenteen energiankulutus
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  input_dimensions: [vehicle, transportation_class]
  output_dimensions: [vehicle, transportation_class]

pages:
- id: home
  name: Hiilineutraali Espoo -päästöskenaario
  path: /
  type: emission
  node: net_emissions
  lead_title: Espoon päästöskenaariot
  lead_title_en: Espoo emission scenarios
  lead_paragraph: '<p>Espoon päästöskenaariot visualisoi Espoon kasvihuonekaasupäästöjen
    kehityksen. Voit tarkastella, mistä Espoon kaupungin alueen päästöt syntyvät ja
    kuinka niiden ennustetaan muuttuvan vuoteen 2030 mennessä. Valittavana on: <b>Suomi
    2035-skenaario</b>, jossa oletetaan, että kansallisella tasolla toteutettavat
    ilmastopolitiikan toimet ja linjaukset vaikuttavat Espoon päästökehitykseen; <b>Hiilineutraali
    Espoo 2030-skenaario (HNE2030)</b>, jossa oletetaan, että kaupungin päästökehitykseen
    vaikuttavat kansallisten toimien lisäksi myös kaupungin ja sen yhteistyökumppaneiden,
    kuten Fortumin ja HSY:n, toteuttamat ilmastotoimet; sekä <b>pessimistinen skenaario</b>
    skenaario, jossa oletetaan, että uusia päästövähennystoimia ei kaupungissa suunnitella
    tai toteuteta.'

actions:
- id: cleaner_electricity_production
  name: Kansallinen sähköntuotanto puhdistuu
  name_en: Shift to low-carbon in national electricity production
  decision_level: nation
  quantity: emission_factor
  output_nodes:
  - electricity_production_emission_factor
  - electric_heating_emission_factor
  type: simple.LinearCumulativeAdditiveAction
  forecast_values: [[2022, 0], [2035, -79.4]]
  unit: g/kWh
  params:
  - id: target_year_level
    values:
      default: -80
    min_value: -85
    max_value: 0
    step: 1
    unit: g/kWh
    description: Sähköntuotannon päästökertoimen muutos 2022-2035
    description_en: Change in electricity production emission factor

- id: change_consumer_electricity
  name: Muutos kulutussähkön käytössä
  type: simple.LinearCumulativeAdditiveAction
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2035, 0]]
  output_nodes:
  - consumer_electricity_residence_energy
  params:
  - id: target_year_level
    min_value: -500
    max_value: 1600
    unit: GWh/a
    description: Kulutussähkön käytön muutos 2022-2035

- id: heating_oil_bioshare
  name: Lämmitysöljyn sekoitusvelvoite
  decision_level: nation
  quantity: emission_factor
  output_nodes:
  - oil_heating_emission_factor
  type: simple.LinearCumulativeAdditiveAction
  forecast_values: [[2022, 0], [2028, -31.9]]
  unit: g/kWh

- id: reduce_oil_heating_residence
  name: Öljylämmityksen vähentäminen (Asuminen)
  type: shift.ShiftAction
  quantity: floor_area
  unit: m**2
  output_dimensions: [building_heat_source, building_use]
  output_nodes:
    - building_floor_area_existing
  params:
  - id: shift
    unit: m**2
    is_customizable: false
    value:
    - source:
        categories:
          building_heat_source: oil
          building_use: residence
      dests:
      - categories:
          building_use: residence
          building_heat_source: geothermal
      - categories:
          building_use: residence
          building_heat_source: district_heat
      amounts:
      - year: 2023
        source_amount: -50000
        dest_amounts: [50, 50]
      - year: 2025
        source_amount: -100000
        dest_amounts: [50, 50]
      - year: 2035
        source_amount: -50000
        dest_amounts: [50, 50]

- id: replace_fossil_fuels_in_district_heating
  name: Fortum korvaa fossiiliset energialähteet kaukolämmöntuotannossa
  name_en: Fortum replaces fossil fuels in district heat production
  type: simple.LinearCumulativeAdditiveAction
  quantity: emission_factor
  output_nodes:
  - district_heating_emission_factor
  forecast_values: [[2021, 0.0], [2025, -82.0], [2030, -116.0]]  # FIXME These do not apply for Suomi2035
  unit: g/kWh

- id: city_building_heat_optimization
  name: Kaupungin kiinteistöjen lämmityksen optimointi
  name_en: Optimization of heating systems in city-owned buildings
  type: simple.CumulativeAdditiveAction
  quantity: energy
  output_nodes:
  - district_heating_energy
  forecast_values: [[2023, -8], [2025, -16], [2026, -4], [2027, -4], [2028, -7], [
      2029, -14], [2030, -6]]
  unit: GWh/a

- id: reduce_waste_treatment_emissions
  name: Jätteiden käsittelyn päästöt pienenevät
  name_en: Waste treatment emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2021, 0], [2030, 0]]
  output_nodes:
  - waste_treatment_emissions
  params:
  - id: target_year_level
    description: Jätteiden käsittelyn päästöjen muutos 2021-2030
    min_value: -30
    max_value: 20
    step: 0.1
    unit: kt/a

- id: reduce_road_transport_emissions
  name: Tieliikenteen päästöt pienenevät
  name_en: Road transportation emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2030, 0]]
  output_nodes:
  - transport_emissions
  params:
  - id: target_year_level
    description: Tieliikenteen päästöjen muutos 2022-2030
    min_value: -100
    max_value: 100
    step: 0.1
    unit: kt/a

- id: reduce_agriculture_emissions
  name: Maatalouden päästöt pienenevät
  name_en: Agriculture emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2035, -0.1079092776]]
  output_nodes:
  - agriculture_emissions

- id: reduce_industrial_fuel_emissions
  name: Teollisuuden polttoaineiden päästöt pienenevät
  name_en: Industrial fuel emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2035, -3.0]]
  output_nodes:
  - industry_fuel_emissions

- id: reduce_machinery_emissions
  name: Työkoneiden päästöt pienenvät
  name_en: Machinery emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2035, 0]]
  output_nodes:
  - machinery_emissions
  params:
  - id: target_year_level
    description: Työkoneiden päästövähennys 2022-2035
    min_value: -3.0
    max_value: 0.0
    unit: kt/a

- id: change_in_car_traffic_energy
  name: Muutos autoliikenteen energiankulutuksessa
  type: simple.LinearCumulativeAdditiveAction
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2035, 0]]
  output_nodes:
  - car_traffic_energy
  params:
  - id: target_year_level
    value: -27.78455812  # FIXME Target year should be 2030 but this value is reached only 2035.

- id: change_in_bus_traffic_energy
  name: Muutos bussiliikenteen energiankulutuksessa
  type: simple.LinearCumulativeAdditiveAction
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2035, 0]]
  output_nodes:
  - bus_traffic_energy
  params:
  - id: target_year_level
    value: 0

- id: change_in_van_traffic_energy
  name: Muutos pakettiautoliikenteen energiankulutuksessa
  type: simple.LinearCumulativeAdditiveAction
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2035, 0]]
  output_nodes:
  - van_traffic_energy
  params:
  - id: target_year_level
    value: -6.886607633

- id: change_in_truck_traffic_energy
  name: Muutos kuorma-autoliikenteen energiankulutuksessa
  type: simple.LinearCumulativeAdditiveAction
  quantity: energy
  unit: GWh/a
  forecast_values: [[2022, 0], [2035, 0]]
  output_nodes:
  - truck_traffic_energy
  params:
  - id: target_year_level
    value: 4.403433483

scenarios:
- id: baseline
  name: Suomi 2035
  name_en: Finland 2035
  params:
  - id: cleaner_electricity_production.enabled
    value: true

  - id: reduce_waste_treatment_emissions.target_year_level
    value: -1.5
  - id: reduce_waste_treatment_emissions.enabled
    value: true

  - id: reduce_road_transport_emissions.target_year_level
    value: -62.4
  - id: reduce_road_transport_emissions.enabled
    value: true

  - id: reduce_machinery_emissions.target_year_level
    value: -0.8
  - id: reduce_machinery_emissions.enabled
    value: true

  - id: change_consumer_electricity.target_year_level
    value: 115
  - id: change_consumer_electricity.enabled
    value: true

  # - id: reduce_oil_heating_services.target_year_level
  #   value: -34
  # - id: reduce_oil_heating_services.enabled
  #   value: true
  # - id: reduce_oil_heating_residence.enabled
  #   value: true
  # - id: reduce_oil_heating_industry.enabled
  #   value: true

- id: default
  default: true
  name: Hiilineutraali Espoo 2030
  name_en: Carbon-neutral Espoo 2030
  all_actions_enabled: true
  params:
  - id: reduce_waste_treatment_emissions.target_year_level
    value: -26.3
  - id: reduce_road_transport_emissions.target_year_level
    value: -67.6
  - id: reduce_machinery_emissions.target_year_level
    value: -2.0
  - id: change_consumer_electricity.target_year_level
    value: 1600
#  - id: change_in_car_traffic_energy.target_year_level
#    value: 27.32404058
  # - id: reduce_oil_heating_services.target_year_level
  #   value: -37

- id: pessimistic
  name: Pessimistinen
  name_en: Pessimistic
  all_actions_enabled: false

#######################
# DATA SOURCES
# Ilmastotiekartan skenaariot_Espoo_09012023.xlsx, sheets:
# DATA_HSY_päästöt: HSY emissions, same as in node all_hsy_emissions
# DATA_HSY_energiankulutus: HSY energy consumption, same as in node all_hsy_emissions
# DATA_HSY_erillislämmitys: HSY data on non-district heating, same as in ####
# DATA_Tilastokeskus_Rakennukset: STATFI building data from
# https://pxdata.stat.fi/PxWeb/pxweb/fi/StatFin/StatFin__rakke/statfin_rakke_pxt_116h.px/
# https://pxdata.stat.fi:443/PxWeb/sq/874cf998-375e-4a64-882b-454ef320fea5
