id: espoo
default_language: fi
supported_languages: [en]
framework: hsy
site_url: https://espoo.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: bf422ab63b0b33090925b2a141d7d275687355a1
name: Hiilineutraali Espoo 2030
name_en: Carbon-neutral Espoo 2030
owner: Espoon kaupunki
owner_en: City of Espoo
theme_identifier: espoo-ilmasto
emission_unit: kt/a
target_year: 2030
reference_year: 1990
minimum_historical_year: 2000
maximum_historical_year: 2021
params:
- id: municipality_name
  value: Espoo

emission_sectors:
- id: net_emissions
  name: Kokonaispäästöt (scope 2)
  name_en: Net emissions (scope 2)
  is_outcome: true
  target_year_goal: 245

- id: building_heating_emissions
  color: '#ff4f57'

- id: consumer_electricity_emissions
  color: '#0047b6'

- id: transport_emissions
  color: '#014B30'

nodes:
- id: population
  type: finland.population.Population
  name: Väestö
  #forecast_values: [[2022, 301866], [2023, 306628], [2024, 311404], [2025, 316189], [2026, 320968], [2027, 325734], [2028, 330474], [2029, 335184], [2030, 339856], [2031, 344488], [2032, 349084], [2033, 353647], [2034, 358180], [2035, 362690]]

- id: all_hsy_emissions
  type: finland.hsy.HsyNode
  name: HSY:n päästöinventaario

#- id: electricity_production_emission_factor
#  type: simple.AdditiveNode
#  name: Kansallisen sähköntuotannon päästökerroin
#  unit: g/kWh
#  quantity: emission_factor
#  input_nodes:
#  - consumer_electricity_residence_emission_factor

pages:
- id: home
  name: Hiilineutraali Espoo -päästöskenaario
  path: /
  type: emission
  node: net_emissions
  lead_title: Espoon päästöskenaariot
  lead_title_en: Espoo emission scenarios
  lead_paragraph: "<p>Espoon päästöskenaariot visualisoi Espoon kasvihuonekaasupäästöjen
    kehityksen. Voit tarkastella, mistä Espoon kaupungin alueen päästöt syntyvät ja
    kuinka niiden ennustetaan muuttuvan vuoteen 2030 mennessä. Valittavana on:
    <b>Suomi 2035-skenaario</b>, jossa oletetaan, että kansallisella tasolla toteutettavat
    ilmastopolitiikan toimet ja linjaukset vaikuttavat Espoon päästökehitykseen; 
    <b>Hiilineutraali Espoo 2030-skenaario (HNE2030)</b>, jossa oletetaan, että kaupungin
    päästökehitykseen vaikuttavat kansallisten toimien lisäksi myös kaupungin ja
    sen yhteistyökumppaneiden, kuten Fortumin ja HSY:n, toteuttamat
    ilmastotoimet; sekä <b>pessimistinen skenaario</b> skenaario, jossa oletetaan, että
    uusia päästövähennystoimia ei kaupungissa suunnitella tai toteuteta."

actions:
- id: cleaner_electricity_production
  name: Kansallinen sähköntuotanto puhdistuu
  name_en: Shift to low-carbon in national electricity production
  decision_level: nation
  quantity: emission_factor
  output_nodes:
  - electricity_production_emission_factor
  type: simple.LinearCumulativeAdditiveAction
  forecast_values: [[2022, 0], [2030, -80]]
  unit: g/kWh
  params:
  - id: target_year_level
    values:
      default: -68
    min_value: -70
    max_value: 0
    step: 1
    unit: g/kWh
    description: Sähköntuotannon päästökertoimen muutos
    description_en: Change in electricity production emission factor

- id: replace_fossil_fuels_in_district_heating
  name: Fortum korvaa fossiiliset energialähteet kaukolämmöntuotannossa
  name_en: Fortum replaces fossil fuels in district heat production
  type: simple.LinearCumulativeAdditiveAction
  quantity: emission_factor
  output_nodes:
  - district_heating_emission_factor
  forecast_values: [[2021, 0], [2025, -82], [2030, -116]]
  unit: g/kWh

- id: city_building_heat_optimization
  name: Kaupungin kiinteistöjen lämmityksen optimointi
  name_en: Optimization of heating systems in city-owned buildings
  type: simple.CumulativeAdditiveAction
  quantity: energy
  output_nodes:
  - district_heating_services_energy
  forecast_values: [[2023, -8], [2025, -16], [2026, -4], [2027, -4], [2028, -7],
    [2029, -14], [2030, -6]]
  unit: GWh/a

- id: reduce_waste_treatment_emissions
  name: Jätteiden käsittelyn päästöt pienenevät
  name_en: Waste treatment emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2030, 0]]
  output_nodes:
  - waste_treatment_emissions
  params:
  - id: target_year_level
    description: Jätteiden käsittelyn päästöjen muutos
    min_value: -20
    max_value: +20
    step: 0.1
    unit: kt/a

- id: reduce_road_transport_emissions
  name: Tieliikenteen päästöt pienenevät
  name_en: Road transportation emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2030, 0]]
  output_nodes:
  - transport_emissions
  params:
  - id: target_year_level
    description: Tieliikenteen päästöjen muutos
    min_value: -100
    max_value: +100
    step: 0.1
    unit: kt/a

- id: reduce_agriculture_emissions
  name: Maatalouden päästöt pienenevät
  name_en: Agriculture emissions are reduced
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2022, 0], [2035, -0.1]]
  output_nodes:
  - agricultural_field_emissions

scenarios:
- id: baseline
  name: Suomi 2035
  name_en: Finland 2035
  params:
  - id: cleaner_electricity_production.enabled
    value: true

  - id: reduce_waste_treatment_emissions.target_year_level
    value: -0.9
  - id: reduce_waste_treatment_emissions.enabled
    value: true

  - id: reduce_road_transport_emissions.target_year_level
    value: -62.4
  - id: reduce_road_transport_emissions.enabled
    value: true

- id: default
  default: true
  name: Hiilineutraali Espoo 2030
  name_en: Carbon-neutral Espoo 2030
  all_actions_enabled: true
  params:
  - id: reduce_waste_treatment_emissions.target_year_level
    value: -16.1
  - id: reduce_road_transport_emissions.target_year_level
    value: -67.6

- id: pessimistic
  name: Pessimistinen
  name_en: Pessimistic
