instance:
  id: ilmastoruoka
  default_language: fi
  dataset_repo: https://github.com/kausaltech/dvctest.git
  name: Suomen ilmastoruokaohjelma
  name_en: Finnish climate food program
  target_year: 2030
  reference_year: 1990
  minimum_historical_year: 2010
  maximum_historical_year: 2018
  emission_dataset: tampere/scenarios/emissions/bau
  emission_unit: kt/day
  emission_forecast_from: 2019
  params:
    - id: municipality_name
      value: Tampere

  emission_sectors:
    - id: net_emissions
      name: Ruoankulutuksen kokonaispäästöt
      name_en: Net emissions from food consumption
      target_year_goal: 2

    - id: other_emissions
      name: Muut
      name_en: Other foods
      part_of: net_emissions
      color: '#668EC9'
      target_year_goal: 115

    - id: alcohol_emissions
      name: Alkoholijuomat
      name_en: Alcohol drinks
      column: Trucks and lorries
      part_of: other_emissions
    - id: drink_emissions
      name: Juomat
      name_en: Drinks
      column: Motorbikes
      part_of: other_emissions
    - id: egg_emissions
      name: Muna
      name_en: Egg
      column: Local trains
      part_of: other_emissions
    - id: fat_emissions
      name: Ravintorasvat
      name_en: Fats
      column: Local trains
      part_of: other_emissions
    - id: spice_emissions
      name: Mausteet
      name_en: Spices
      column: Local trains
      part_of: other_emissions
    - id: potato_emissions
      name: Perunat
      name_en: Potato
      column: Local trains
      part_of: other_emissions
    - id: sugar_emissions
      name: Sokerit ja makeiset
      name_en: Sugar and sweets
      column: Local trains
      part_of: other_emissions

    - id: grain_emissions
      name: Viljatuotteiden päästöt
      name_en: Grain emissions
      part_of: net_emissions
      color: '#AD3963'
      target_year_goal: 50

    - id: fish_emissions
      name: Kalan päästöt
      name_en: Fish emissions
      part_of: net_emissions
      color: '#E8B455'
      target_year_goal: 50

  nodes:
    - id: population
      type: finland.Population
      name: Väestö

    - id: other_grain_emissions
      name: Muiden viljatuotteiden päästöt
      name_en: Other grain emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 1.8514 # FIXIT Does not accept unit kg/kg. Is this because quantities differ?
      output_nodes:
        - grain_emissions

    - id: other_grain_consumption_per_capita
      name: Viljan kulutus per henkilö
      name_en: Grain consumption per person
      type: simple.AdditiveNode
      quantity: per_capita
      unit: g/day/person
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: false
      output_nodes:
        - other_grain_consumption

    - id: other_grain_consumption
      name: Viljan kulutus
      name_en: Grain consumption
      type: simple.PerCapitaActivity
      quantity: mass
      unit: t/day # FIXIT Does dvctest not know the unit in the data?
      input_nodes:
        - population
      output_nodes:
        - other_grain_emissions

#    - id: other_electricity_consumption
#      name: Muu sähkönkulutus
#      name_en: Other electricity consumption
#      type: simple.PerCapitaActivity
#      unit: GWh
#      quantity: energy
#      input_nodes:
#        - population
#      output_nodes:
#        - other_electricity_consumption_emissions

    - id: imported_fish_emissions
      name: Tuontikalan päästöt
      name_en: Imported fish emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 5.2681 # FIXIT Does not accept unit kg/kg. Is this because quantities differ?
      output_nodes:
        - fish_emissions

    - id: imported_fish_consumption
      name: Tuontikalan kulutus
      name_en: Imported fish consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - imported_fish_emissions

    - id: fruit_emissions
      name: Hedelmien ja marjojen päästöt
      name_en: Fruit and berry emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      color: '#397368'
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 1.0626
      output_nodes:
        - net_emissions

    - id: fruit_consumption
      name: Hedelmien ja marjojen kulutus
      name_en: Fruit and berry consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - fruit_emissions

    - id: meat_emissions
      name: Lihan päästöt
      name_en: Meat emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      color: '#ABC872'
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 19.2005
      output_nodes:
        - net_emissions

    - id: meat_consumption
      name: Lihan kulutus
      name_en: Meat consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - meat_emissions

    - id: legume_emissions
      name: Palkokasvien ja pähkinöiden päästöt
      name_en: Legume and nut emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      color: '#BBC862'
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 3.2852
      output_nodes:
        - net_emissions

    - id: legume_consumption
      name: Palkokasvien ja pähkinöiden kulutus
      name_en: Legume and nut consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - legume_emissions

    - id: dairy_emissions
      name: Maitotuotteiden päästöt
      name_en: Milk and dairy emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      color: '#CBC852'
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 2.1613
      output_nodes:
        - net_emissions

    - id: dairy_consumption
      name: maitotuotteiden kulutus
      name_en: Milk and dairy consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - dairy_emissions

    - id: vegetable_emissions
      name: Vihannesten päästöt
      name_en: Vegetable emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      color: '#DBC842'
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 1.7156
      output_nodes:
        - net_emissions

    - id: vegetable_consumption
      name: Vihannesten kulutus
      name_en: Vegetable consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - vegetable_emissions

    - id: oatdrink_emissions
      name: Kaurajuoman päästöt
      name_en: Oatdrink emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/d
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 1.2928
      output_nodes:
        - grain_emissions

    - id: oatdrink_consumption
      name: Kaurajuoman kulutus
      name_en: Oatdrink consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - oatdrink_emissions

    - id: domestic_fish_emissions
      name: Kotimaisen kalan päästöt
      name_en: Domestic fish emissions
      type: simple.FixedMultiplierNode
      quantity: emissions
      unit: kt/a
      target_year_goal: 1
      params: 
        - id: multiplier
          value: 3.5422
      output_nodes:
        - fish_emissions

    - id: domestic_fish_consumption
      name: Kotimaisen kalan kulutus
      name_en: Domestic fish consumption
      type: simple.AdditiveNode
      quantity: mass
      unit: kt/a 
      input_datasets:
        - id: tampere/scenarios/activity/bau
          column: District heating
          dropna: true
      output_nodes:
        - domestic_fish_emissions

################

#    - id: other_electricity_consumption_per_capita
#      name: Sähkönkulutus asukasta kohti
#      name_en: Electricity consumption per capita
#      type: simple.AdditiveNode
#      unit: kWh/person
#      quantity: per_capita
#      input_datasets:
#        - id: tampere/scenarios/activity/bau
#          column: Other electricity consumption per capita
#      output_nodes:
#        - other_electricity_consumption

#    - id: other_electricity_consumption
#      name: Muu sähkönkulutus
#      name_en: Other electricity consumption
#      type: simple.PerCapitaActivity
#      unit: GWh
#      quantity: energy
#      input_nodes:
#        - population
#      output_nodes:
#        - other_electricity_consumption_emissions

    - id: pm_emissions
      name: Pienhiukkaspäästöt
      name_en: Fine particle emissions
      type: simple.AdditiveNode
      quantity: emissions
      unit: ug/m**3
      historical_values: [[2018, 1], [2019, 1], [2020, 1]]
      forecast_values: [[2021, 1], [2022, 1], [2023, 1], [2024, 1], [2025, 1], [2026, 1], [2027, 1], [2028, 1], [2029, 1], [2030, 1]]

    - id: pm_exposure
      name: Pienhiukkasaltistus
      name_en: Fine particle exposure
      type: simple.FixedMultiplierNode
      quantity: exposure
      unit: ug/m**3
      params:
        - id: multiplier
          value: 1.1
      input_nodes:
        - pm_emissions
      output_nodes:
        - rr_cvd_mortality

    - id: rr_cvd_mortality
      name: Sydänkuolleisuuden suhteellinen riski
      name_en: Relative risk of cardiovascular mortality
      type: simple.RelativeRiskNode
      quantity: ratio
      unit: dimensionless
      params:
        - id: exposure_response_param1
          value: 0.008959741 m**3/microgram
        - id: exposure_response_param2
          value: 0 microgram/m**3

    - id: pm_exposed_fraction
      name: Altistuneiden osuus
      name_en: Exposed fraction
      type: simple.AdditiveNode
      quantity: ratio
      unit: dimensionless
      historical_values: [[2018, 0.5], [2019, 0.5], [2020, 0.5]]
      forecast_values: [[2021, 0.5], [2022, 0.5], [2023, 0.5], [2024, 0.5], [2025, 0.5], [2026, 0.5], [2027, 0.5], [2028, 0.5], [2029, 0.5], [2030, 0.5]]

    - id: paf_cvd_mortality
      name: Väestösyyosuus
      name_en: Population attributable fraction
      type: simple.PopulationAttributableFractionNode
      quantity: ratio
      unit: dimensionless
      input_nodes: 
        - rr_cvd_mortality
        - pm_exposed_fraction

    - id: disease_burden
      name: Tautitaakka
      name_en: Disease burden
      type: simple.AdditiveNode
      quantity: disease_burden
      unit: DALY
      historical_values: [[2018, 0.5], [2019, 0.5], [2020, 0.5]]
      forecast_values: [[2021, 0.5], [2022, 0.5], [2023, 0.5], [2024, 0.5], [2025, 0.5], [2026, 0.5], [2027, 0.5], [2028, 0.5], [2029, 0.5], [2030, 0.5]]

    - id: attributable_disease_burden
      name: Kohdentuva tautitaakka
      name_en: Attributable disease burden
      type: simple.Multiple2Node
      quantity: disease_burden
      unit: DALY
      input_nodes:
        - paf_cvd_mortality
        - disease_burden


#    - id: pm_emission_factor # FIXIT: This is not a simple time series
#      name: Pienhiukkasten päästökerroin
#      name_en: Fine particle emission factor
#      type: simple.AdditiveNode
#      unit: ug/m**3
#      input_datasests:
#        - id: vtt/lipasto/car_unit_emissions
#          column: PM
#      output_nodes:
#        - pm_exposure

  #
  # ------- ACTIONS --------
  #

  actions:

#    - id: naistenlahti3
#      name: Naistenlahti 3 -biovoimalaitos
#      name_en: Naistenlahti 3 bio thermal plant
#      type: simple.CumulativeAdditiveAction
#      quantity: emission_factor
#      output_nodes:
#        - district_heating_emission_factor
#      forecast_values: [[2022, -23], [2023, -23]]
#      unit: g/kWh

    - id: grain_consumption_change
      name: Viljojen kulutus muuttuu
      name_en: Grain consumption change
      quantity: per_capita
      output_nodes:
        - other_grain_consumption_per_capita
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: g/day/person
      params:
        - id: target_year_level
          values:
            default: 0
          min_value: 0
          max_value: 140
          step: 1
          unit: g/day/person
          description: Viljan kulutuksen muutos
          description_en: Change in grain consumption

    - id: imported_fish_consumption_change
      name: Kalan kulutus muuttuu
      name_en: Fish consumption change
#      decision_level: nation
      quantity: mass
      output_nodes:
        - imported_fish_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: 0
          min_value: -31
          max_value: 60
          step: 1
          unit: kt/a
          description: Kalan kulutuksen muutos
          description_en: Change in fish consumption

    - id: fruit_consumption_change
      name: Hedelmien ja marjonen kulutus muuttuu
      name_en: Fruit and berry consumption change
      quantity: mass
      output_nodes:
        - fruit_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Hedelmien ja marjojen kulutuksen muutos
          description_en: Change in fruit and berry consumption

    - id: meat_consumption_change
      name: Lihan kulutus muuttuu
      name_en: Meat consumption change
      quantity: mass
      output_nodes:
        - meat_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Lihan kulutuksen muutos
          description_en: Change in meat consumption

    - id: legume_consumption_change
      name: Palkokasvien ja pähkinöiden kulutus muuttuu
      name_en: Legume and nut consumption change
      quantity: mass
      output_nodes:
        - legume_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Palkokasvien ja pähkinöiden kulutuksen muutos
          description_en: Change in legume and nut consumption

    - id: dairy_consumption_change
      name: Maitotuotteiden kulutus muuttuu
      name_en: Dairy product consumption change
      quantity: mass
      output_nodes:
        - dairy_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Maitotuotteiden kulutuksen muutos
          description_en: Change in dairy consumption

    - id: vegetable_consumption_change
      name: Vihannesten kulutus muuttuu
      name_en: Vegetable consumption change
      quantity: mass
      output_nodes:
        - vegetable_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Vihannesten kulutuksen muutos
          description_en: Change in vegetable consumption

    - id: oatdrink_consumption_change
      name: Kaurajuoman kulutus muuttuu
      name_en: Oatdrink consumption change
      quantity: mass
      output_nodes:
        - oatdrink_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Kaurajuoman kulutuksen muutos
          description_en: Change in oatdrink consumption

    - id: domestic_fish_consumption_change
      name: Kotimaisen kalan kulutus muuttuu
      name_en: Domestic fish consumption change
      quantity: mass
      output_nodes:
        - domestic_fish_consumption
      type: simple.LinearCumulativeAdditiveAction
      forecast_values: [[2019, 0], [2030, -500]]
      unit: kt/a
      params:
        - id: target_year_level
          values:
            default: -400
          min_value: -1000
          max_value: 0
          step: 10
          unit: kt/a
          description: Kotimaisen kalan kulutuksen muutos
          description_en: Change in domestic fish consumption

  pages:
    - id: home
      name: Hiilineutraali Tampere 2030 -päästöskenaario
      path: '/'
      type: emission
      node: net_emissions

  scenarios:
    - id: baseline
      name: Nykykehitys
      name_en: Baseline
      params:
        - id: imported_fish_consumption_change.enabled
          value: true
#        - id: cleaner_electricity_production.enabled
#          value: true

    - id: default
      default: true
      name: Hiilineutraali Tampere 2030 -tiekartta
      name_en: Carbon-neutral Tampere 2030 roadmap
      all_actions_enabled: true
