id: lappeenranta-syke
default_language: fi
supported_languages: [en]
frameworks: [syke]
site_url: https://lappeenranta-syke.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  dvc_remote: kausal-s3
  commit: 136cbabc5f5441f4280d2a4974cc3923525f4789
theme_identifier: lpr-ilmasto
name: Lappeenrannan ilmasto-ohjelma 2030
name_en: Lappeenranta Climate Action Plan 2030
owner: Lappeenrannan kaupunki
owner_en: City of Lappeenranta
emission_unit: kt/a
target_year: 2030
model_end_year: 2030
reference_year: 2005
minimum_historical_year: 2010

params:
- id: municipality_name
  value: Lappeenranta
- id: extend_historical_values
  value: true
- id: selected_framework
  value: Hinku-laskenta päästöhyvityksillä
  # Currently available options:
  # Hinku-laskenta ilman päästöhyvityksiä
  # Hinku-laskenta päästöhyvityksillä
  # Kaikki ALas-päästöt
  # Taakanjakosektorin kaikki ALas-päästöt
  # Päästökaupan alaiset ALas-päästöt

dimensions:
- id: pollutant
  label: Saaste
  alias: transport_pollutant
  categories:
  - id: co2
    label: CO2
  - id: pm25
    label: PM2.5
    alias: pm2_5
  - id: nox
    label: NOx
  - id: pm10
    label: PM10
  - id: dioxin
    label: Dioksiini
  - id: omega3
    label: Omega-3
  - id: vitamin_d
    label: D-vitamiini
  - id: campylobacter
    label: Kampylobakteeri
  - id: rotavirus
    label: Rotavirus
  - id: norovirus
    label: Norovirus
  - id: sapovirus
    label: Sapovirus
  - id: cryptosporidium
    label: Cryptosporidium
  - id: e_coli
    label: E. coli
  - id: giardia
    label: Giardia
  - id: walking
    label: Kävely
  - id: cycling
    label: Pyöräily
  - id: pm1025
    label: PM10-PM2.5
  - id: so2
    label: SO2
  - id: nh3
    label: NH3

- id: response
  label: Terveysvaikutus
  categories:
  - id: mortality
    label: Kuolleisuus
  - id: work_days_lost
    label: Menetetyt työpäivät
  - id: chronic_bronchitis
    label: Chronic bronchitis
  - id: cancer
    label: Syöpä
  - id: tolerable_weekly_intake
    label: Siedettävä viikkosaanti
  - id: chd_mortality
    label: Sepelvaltimotautikuolleisuus
  - id: breast_cancer
    label: Rintasyöpä
  - id: deficiency
    label: Puutos
  - id: infection
    label: Infektio

emission_sectors:
- id: net_emissions
  name: Kokonaispäästöt (scope 1+2)
  name_en: Net emissions (scope 1+2)
  description: 'Päästötavoitteena on olla hiilineutraali vuonna 2030. Päästöistä vähennetään
    vähintään 80 % verrattuna vuoden 2020 tilanteeseen (363,7 kt) ja korkeintaan 20
    % (72,7 kt) kompensoidaan. (Lähde: Lappeenrannan Climate City Contract)'
  is_outcome: true
  target_year_goal: 72.7

nodes:
- id: population
  type: finland.Population
  name: Väestö

- id: all_alas_emissions
  type: finland.syke.AlasNode
  name: SYKE:n ALaS-päästöinventaario

- id: attributable_fraction
  name: Attributable fraction
  type: health.AttributableFractionRR
  quantity: exposure_response
  unit: dimensionless
  input_dimensions: [response, pollutant]
  output_dimensions: [response, pollutant]
  input_datasets:
  - id: hia/exposure_response/air_pollution_erf
    filters:
    - column: Route
      value: inhalation
  input_nodes:
  - id: exposure
    to_dimensions:
    - id: pollutant
  params:
  - id: gpc_sector
    value: Air pollution

- id: intake_fraction
  name: Saantiosuus
  type: gpc.DatasetNode2
  quantity: fraction
  unit: ppm
  input_dimensions: [pollutant]
  output_dimensions: [pollutant]
  input_datasets:
  - id: hia/intake_fraction/air_pollution_if
    filters:
    - column: Population density
      value: average
    - column: Emission height
      value: average
  params:
  - id: gpc_sector
    value: Air pollution

- id: emission_ratio
  name: Päästöjen suhde
  type: gpc.DatasetRatioNode
  quantity: emission_factor
  unit: dimensionless
  input_dimensions: [pollutant]
  output_dimensions: [pollutant]
  input_datasets:
  - id: nzc/defaults/transport
    forecast_from: 2023
    filters:
    - column: Transport mode
      value: cars
  params:
  - id: gpc_sector
    value: baseline year fleet emission factor
  - id: reference_category
    value: 'transport_pollutant:co2'

- id: transport_air_pollution_emissions
  name: Liikenteen ilmansaastepäästöt
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [pollutant]
  output_dimensions: [pollutant]
  input_nodes:
  - id: transport_emissions
    tags: [non_additive]
    to_dimensions: []
  - id: emission_ratio

- id: breathing_rate
  name: Hengitystilavuus
  type: simple.AdditiveNode
  quantity: mass
  unit: m**3/person/d
  historical_values: [[1990, 20], [2023, 20]]
  input_dataset_processors: [LinearInterpolation]

- id: exposure
  name: Exposure
  type: simple.MultiplicativeNode
  quantity: exposure
  unit: ug/m**3
  input_dimensions: [pollutant]
  output_dimensions: [pollutant]
  input_nodes:
  - id: transport_air_pollution_emissions
  - id: intake_fraction
  - id: breathing_rate
    tags: [geometric_inverse]
    to_dimensions: []
  - id: population
    tags: [geometric_inverse]
    to_dimensions: []

- id: incidence
  name: Ilmaantuvuus
  type: gpc.DatasetNode2
  quantity: incidence
  unit: case/personyear
  input_dimensions: [response]
  output_dimensions: [response]
  input_datasets:
  - id: hia/incidence/default_incidence
    filters:
    - column: Place
      value: default
    - column: Population
      value: default
  params:
  - id: gpc_sector
    value: Environmental health

- id: disease_burden
  name: Kokonaistautitaakka
  type: simple.MultiplicativeNode
  quantity: disease_burden
  unit: DALY/a
  input_dimensions: [response]
  output_dimensions: [response]
  input_nodes:
  - id: incidence
  - id: case_burden
    to_dimensions:
    - id: response
  - id: population
    to_dimensions: []

- id: case_burden
  name: Tapaustautitaakka
  type: gpc.DatasetNode2
  quantity: case_burden
  unit: DALY/case
  input_dimensions: [response]
  output_dimensions: [response]
  input_datasets:
  - id: hia/exposure_response/air_pollution_erf
  params:
  - id: gpc_sector
    value: Air pollution

- id: disease_burden_of_air_pollution
  name: Ilmansaasteiden tautitaakka
  type: simple.MultiplicativeNode
  quantity: disease_burden
  unit: DALY/a
  input_dimensions: [response, pollutant]
  output_dimensions: [response, pollutant]
  input_nodes:
  - id: disease_burden
    tags: [non_additive]
    to_dimensions:
    - id: response
  - id: attributable_fraction

actions:
- id: test
  name: test
  type: simple.AdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2023, 100.0]]

pages:
- id: home
  name: Hiilineutraali Lappeenranta -päästöskenaario
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Lappeenrannan päästöskenaariot
  lead_title_en: Lappeenranta emission scenarios
  lead_paragraph: Lappeenrannan päästöskenaariot visualisoi Lappeenrannan kasvihuonekaasupäästöjen
    kehityksen. Voit tarkastella, mistä Lappeenrannan kaupungin alueen päästöt syntyvät
    ja kuinka niiden ennustetaan muuttuvan vuoteen 2030 mennessä. Valittavana on peruskehitys-skenaario,
    Lappeenrannan ilmasto-ohjelman mukainen skenaario sekä skenaario, jota voit itse
    muokata. Hiilineutraaliksi pääseminen edellyttää vielä lisää toimia, ja niiden
    riittävyyttä arvioidaan jatkossa tämän työkalun avulla.

scenarios:
- id: baseline
  name: Nykykehitys
  name_en: Baseline

- id: default
  default: true
  name: Lappeenrannan ilmasto-ohjelma
  name_en: Lappeenranta Climate Action Plan
