id: potsdam-gpc
default_language: de
supported_languages: []
site_url: https://potsdam-gpc.paths.staging.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: a7756e03df2e4ae18887bd2ca4dc83a3b98a89d4
  dvc_remote: kausal-s3
name: Potsdam BASIC+ Treibhausgasinventur
owner: Stadt Potsdam
theme_identifier: de-potsdam
target_year: 2050
model_end_year: 2050
minimum_historical_year: 1995
maximum_historical_year: 2022
emission_unit: t/a
emission_forecast_from: 2023
emission_dimensions: [energietrager, scope, ghg]
features:
  baseline_visible_in_graphs: true
params:
- id: weather_normalization
  value: true
  is_customizable: true
  is_visible: true

action_groups:
- id: stationary
  name: Stationär
  color: '#989898'
- id: transport
  name: Transport
  color: '#0505A0'
- id: waste
  name: Abfall
  color: '#007C78'
- id: afolu
  name: AFOLU
  color: '#cccccc'

dimensions:
- id: ghg
  label: THG
  categories:
  - id: co2e
    label: CO2e

- id: energietrager
  label: Energieträger
  categories:
  - id: strom
    label: Strom
  - id: fahrstrom
    label: Fahrstrom
  - id: heizstrom
    label: Heizstrom
  - id: fernwarme
    label: Fernwärme
  - id: nahwarme
    label: Nahwärme
  - id: gas
    label: Gas
  - id: biogas
    label: Biogas
  - id: heizol
    label: Heizöl
  - id: kohle
    label: Kohle
  - id: biomasse
    label: Biomasse
  - id: solarthermie
    label: Solarthermie
  - id: umweltwarme
    label: Umweltwärme
  - id: benzin_fossil
    label: Benzin_fossil
  - id: benzin_biogen
    label: Benzin_biogen
  - id: diesel_fossil
    label: Diesel fossil
  - id: diesel_biogen
    label: Diesel biogen
  - id: cng_fossil
    label: CNG fossil
  - id: lpg
    label: LPG
  - id: wasserstoff
    label: Wasserstoff

- id: scope
  label: Scope
  categories:
  - id: scope1
    label: scope1
  - id: scope2
    label: scope2

emission_sectors:
- id: net_emissions
  name: Netemissionen
  is_outcome: true


nodes:
- id: witterungsbereinigung
  name: Witterungsbereinigung
  type: gpc.WeatherNode
  quantity: ratio
  unit: dimensionless
#  output_dimensions: [energietrager]
  historical_values: [[1995, 1], [1999, 1], [2003, 1], [2008, 1], [2012, 1], [2014,
      0.95], [2017, 0.9], [2020, 0.8]]
#  input_datasets:  # FIXME For some reason, the unit gets lost
#  - id: gpc/potsdam_witterungsbereinigung
#    column: factor  # FIXME Updated dataset has 'ratio' but this only works with the old column name?!?
#    forecast_from: 2023
  params:
  - id: weather_normalization
    ref: weather_normalization
  output_nodes:
  - id: i11_residential_fuel_consumption
    tags: non_additive
    to_dimensions:
    - id: energietrager
      categories: [gas]  # FIXME Should apply to all categories
    - id: scope
      categories: [scope1]

- id: i11_residential_fuel_consumption
  name: I.1.1 Wohnkraftstoffverbrauch
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  params:
    gpc_sector: I.1.1
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
#  input_dataset_processors: [LinearInterpolation]  # FIXME Time series is broken but this line would cause an error
  output_nodes:
  - id: i11_residential_fuel_consumption_emissions
    tags: [non_additive]
    to_dimensions:
    - id: energietrager
    - id: scope

- id: i11_residential_fuel_consumption_emissions
  name: I.1.1 Wohnkraftstoffverbrauchemissionen
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i11_residential_fuel_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i11_residential_fuel_emission_factor
  name: I.1.1 Wohnkraftstoffemissionsfaktor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energietrager, scope]
  output_dimensions: [ghg, energietrager, scope]
  params:
    gpc_sector: I.1.1
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: i11_residential_fuel_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energietrager
    - id: scope

- id: i12_residential_grid_energy_consumption
  name: I.1.2 Wohnnetzenergieverbrauch
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  params:
    gpc_sector: I.1.2
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: i12_residential_grid_energy_consumption_emissions
    to_dimensions:
    - id: energietrager
    - id: scope

- id: i12_residential_grid_energy_consumption_emissions
  name: I.1.2 Wohnnetzenergieverbrauchemissionen
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i12_residential_grid_energy_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i12_residential_grid_energy_emission_factor
  name: I.1.2 Wohnnetzenergieemissionsfaktor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energietrager, scope]
  output_dimensions: [ghg, energietrager, scope]
  params:
    gpc_sector: I.1.2
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: i12_residential_grid_energy_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energietrager
    - id: scope

- id: i42_energy_grid_energy_consumption
  name: I.4.2 Energienetzenergieverbrauch
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  params:
    gpc_sector: I.4.2
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: i42_energy_grid_energy_consumption_emissions
    to_dimensions:
    - id: energietrager
    - id: scope

- id: i42_energy_grid_energy_consumption_emissions
  name: I.4.2 Energienetzenergieverbrauchemissionen
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i42_energy_grid_energy_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i42_energy_grid_energy_emission_factor
  name: I.4.2 Energienetzenergieemissionsfaktor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energietrager, scope]
  output_dimensions: [ghg, energietrager, scope]
  params:
    gpc_sector: I.4.2
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: i42_energy_grid_energy_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energietrager
    - id: scope

- id: ii11_onroad_transport_fuel_consumption
  name: II.1.1 Straßentransportkraftstoffverbrauch
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  params:
    gpc_sector: II.1.1
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: ii11_onroad_transport_fuel_consumption_emissions
    to_dimensions:
    - id: energietrager
    - id: scope

- id: ii11_onroad_transport_fuel_consumption_emissions
  name: II.1.1 Straßentransportkraftstoffverbrauchemissionen
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: ii11_onroad_transport_fuel_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: ii11_onroad_transport_fuel_emission_factor
  name: II.1.1 Straßentransportkraftstoffemissionsfaktor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energietrager, scope]
  output_dimensions: [ghg, energietrager, scope]
  params:
    gpc_sector: II.1.1
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: ii11_onroad_transport_fuel_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energietrager
    - id: scope

- id: ii12_onroad_transport_grid_energy_consumption
  name: II.1.2 Straßentransportnetzenergieverbrauch
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  params:
    gpc_sector: II.1.2
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: ii12_onroad_transport_grid_energy_consumption_emissions
    to_dimensions:
    - id: energietrager
    - id: scope

- id: ii12_onroad_transport_grid_energy_consumption_emissions
  name: II.1.2 Straßentransportnetzenergieverbrauchemissionen
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: ii12_onroad_transport_grid_energy_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: ii12_onroad_transport_grid_energy_emission_factor
  name: II.1.2 Straßentransportnetzenergieemissionsfaktor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energietrager, scope]
  output_dimensions: [ghg, energietrager, scope]
  params:
    gpc_sector: II.1.2
  input_datasets:
  - id: gpc/potsdam
    forecast_from: 2023
  output_nodes:
  - id: ii12_onroad_transport_grid_energy_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energietrager
    - id: scope

- id: i11_residential_fuel_total_emissions
  name: I.1.1 Wohnkraftstoffgesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i1_residential_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i12_residential_grid_energy_total_emissions
  name: I.1.2 Wohnnetzenergiegesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i1_residential_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i1_residential_total_emissions
  name: I.1 Wohngesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i_stationary_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i42_energy_grid_energy_total_emissions
  name: I.4.2 Energienetzenergiegesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i4_energy_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i4_energy_total_emissions
  name: I.4 Energiegesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: i_stationary_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: i_stationary_total_emissions
  name: I Stationärgesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: net_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: ii11_onroad_transport_fuel_total_emissions
  name: II.1.1 Straßentransportkraftstoffgesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: ii1_onroad_transport_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: ii12_onroad_transport_grid_energy_total_emissions
  name: II.1.2 Straßentransportnetzenergiegesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: ii1_onroad_transport_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: ii1_onroad_transport_total_emissions
  name: II.1 Straßentransportgesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: ii_transportation_total_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

- id: ii_transportation_total_emissions
  name: II Transportgesamtemissionen
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energietrager, scope, ghg]
  output_dimensions: [energietrager, scope, ghg]
  output_nodes:
  - id: net_emissions
    to_dimensions:
    - id: energietrager
    - id: scope
    - id: ghg

actions:

- id: i11_residential_fuel_consumption_action
  name: I.1.1 Wohnkraftstoffverbrauchaktion
  type: gpc.DatasetAction
  quantity: energy
  unit: MWh/a
  group: stationary
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, scope]
  params:
  - id: gpc_sector
    value: I.1.1
  output_nodes: [i11_residential_fuel_consumption]

- id: i11_residential_fuel_emission_factor_action
  name: I.1.1 Wohnkraftstoffemissionsfaktoraktion
  type: gpc.DatasetAction
  quantity: emission_factor
  unit: t/MWh
  group: stationary
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, ghg, scope]
  params:
  - id: gpc_sector
    value: I.1.1
  output_nodes: [i11_residential_fuel_emission_factor]

- id: i12_residential_grid_energy_consumption_action
  name: I.1.2 Wohnnetzenergieverbrauchaktion
  type: gpc.DatasetAction
  quantity: energy
  unit: MWh/a
  group: stationary
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, scope]
  params:
  - id: gpc_sector
    value: I.1.2
  output_nodes: [i12_residential_grid_energy_consumption]

- id: i12_residential_grid_energy_emission_factor_action
  name: I.1.2 Wohnnetzenergieemissionsfaktoraktion
  type: gpc.DatasetAction
  quantity: emission_factor
  unit: t/MWh
  group: stationary
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, ghg, scope]
  params:
  - id: gpc_sector
    value: I.1.2
  output_nodes: [i12_residential_grid_energy_emission_factor]

- id: i42_energy_grid_energy_consumption_action
  name: I.4.2 Energienetzenergieverbrauchaktion
  type: gpc.DatasetAction
  quantity: energy
  unit: MWh/a
  group: stationary
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, scope]
  params:
  - id: gpc_sector
    value: I.4.2
  output_nodes: [i42_energy_grid_energy_consumption]

- id: i42_energy_grid_energy_emission_factor_action
  name: I.4.2 Energienetzenergieemissionsfaktoraktion
  type: gpc.DatasetAction
  quantity: emission_factor
  unit: t/MWh
  group: stationary
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, ghg, scope]
  params:
  - id: gpc_sector
    value: I.4.2
  output_nodes: [i42_energy_grid_energy_emission_factor]

- id: ii11_onroad_transport_fuel_consumption_action
  name: II.1.1 Straßentransportkraftstoffverbrauchaktion
  type: gpc.DatasetAction
  quantity: energy
  unit: MWh/a
  group: transport
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, scope]
  params:
  - id: gpc_sector
    value: II.1.1
  output_nodes: [ii11_onroad_transport_fuel_consumption]

- id: ii11_onroad_transport_fuel_emission_factor_action
  name: II.1.1 Straßentransportkraftstoffemissionsfaktoraktion
  type: gpc.DatasetAction
  quantity: emission_factor
  unit: t/MWh
  group: transport
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, ghg, scope]
  params:
  - id: gpc_sector
    value: II.1.1
  output_nodes: [ii11_onroad_transport_fuel_emission_factor]

- id: ii12_onroad_transport_grid_energy_consumption_action
  name: II.1.2 Straßentransportnetzenergieverbrauchaktion
  type: gpc.DatasetAction
  quantity: energy
  unit: MWh/a
  group: transport
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, scope]
  params:
  - id: gpc_sector
    value: II.1.2
  output_nodes: [ii12_onroad_transport_grid_energy_consumption]

- id: ii12_onroad_transport_grid_energy_emission_factor_action
  name: II.1.2 Straßentransportnetzenergieemissionsfaktoraktion
  type: gpc.DatasetAction
  quantity: emission_factor
  unit: t/MWh
  group: transport
  input_datasets:
  - id: gpc/potsdam_master_plan_actions
    forecast_from: 2022
  output_dimensions: [energietrager, ghg, scope]
  params:
  - id: gpc_sector
    value: II.1.2
  output_nodes: [ii12_onroad_transport_grid_energy_emission_factor]

pages:
- id: home
  name: Potsdam BASIC+ Treibhausgasinventur
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Potsdam Zielwerte Masterplan
  lead_paragraph: GPC BASIC+ Treibhausgasinventur (1995–2022) und Prognose (2023–2050)
    for the City of Potsdam.

scenarios:
- id: baseline
  name: Wie gewohnt

- id: default
  default: true
  name: Klimaaktionplan
  all_actions_enabled: true
