id: potsdam-gpc
default_language: de
supported_languages: []
site_url: https://potsdam-gpc.paths.staging.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 225590bd10735cb2ed99d1a969dc79064452d81c
  dvc_remote: kausal-s3
name: Potsdam BASIC+ Greenhouse Gas Inventory
owner: City of Potsdam
theme_identifier: default
target_year: 2050
model_end_year: 2050
minimum_historical_year: 1995
maximum_historical_year: 2022
emission_unit: t/a
emission_forecast_from: 2023
emission_dimensions: [energitrager, scope, ghg]
features:
  baseline_visible_in_graphs: true

dimensions:
- id: ghg
  label: GHG
  categories:
  - id: co2e
    label: co2e

- id: energitrager
  label: Energiträger
  categories:
  - id: benzin_biogen
    label: benzin_biogen
  - id: benzin_fossil
    label: benzin_fossil
  - id: biogas
    label: biogas
  - id: biomasse
    label: biomasse
  - id: cng_fossil
    label: cng_fossil
  - id: diesel_biogen
    label: diesel_biogen
  - id: diesel_fossil
    label: diesel_fossil
  - id: fahrstrom
    label: fahrstrom
  - id: fernwarme
    label: fernwärme
  - id: gas
    label: gas
  - id: heizstrom
    label: heizstrom
  - id: heizol
    label: heizöl
  - id: kohle
    label: kohle
  - id: lpg
    label: lpg
  - id: nahwarme
    label: nahwärme
  - id: solarthermie
    label: solarthermie
  - id: strom
    label: strom
  - id: umweltwarme
    label: umweltwärme
  - id: wasserstoff
    label: wasserstoff

- id: scope
  label: Scope
  categories:
  - id: scope1
    label: scope1
  - id: scope2
    label: scope2

emission_sectors:
- id: net_emissions
  name: Net Emissions
  is_outcome: true


nodes:
- id: i11_residential_fuel_consumption
  name: I.1.1 Residential Fuel Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energitrager, scope]
  output_dimensions: [energitrager, scope]
  params:
    gpc_sector: I.1.1
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: i11_residential_fuel_consumption_emissions
    to_dimensions:
    - id: energitrager
    - id: scope

- id: i11_residential_fuel_consumption_emissions
  name: I.1.1 Residential Fuel Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i11_residential_fuel_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i11_residential_fuel_emission_factor
  name: I.1.1 Residential Fuel Emission Factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energitrager, scope]
  output_dimensions: [ghg, energitrager, scope]
  params:
    gpc_sector: I.1.1
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: i11_residential_fuel_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energitrager
    - id: scope

- id: i12_residential_grid_energy_consumption
  name: I.1.2 Residential Grid Energy Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energitrager, scope]
  output_dimensions: [energitrager, scope]
  params:
    gpc_sector: I.1.2
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: i12_residential_grid_energy_consumption_emissions
    to_dimensions:
    - id: energitrager
    - id: scope

- id: i12_residential_grid_energy_consumption_emissions
  name: I.1.2 Residential Grid Energy Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i12_residential_grid_energy_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i12_residential_grid_energy_emission_factor
  name: I.1.2 Residential Grid Energy Emission Factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energitrager, scope]
  output_dimensions: [ghg, energitrager, scope]
  params:
    gpc_sector: I.1.2
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: i12_residential_grid_energy_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energitrager
    - id: scope

- id: i42_energy_grid_energy_consumption
  name: I.4.2 Energy Grid Energy Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energitrager, scope]
  output_dimensions: [energitrager, scope]
  params:
    gpc_sector: I.4.2
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: i42_energy_grid_energy_consumption_emissions
    to_dimensions:
    - id: energitrager
    - id: scope

- id: i42_energy_grid_energy_consumption_emissions
  name: I.4.2 Energy Grid Energy Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i42_energy_grid_energy_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i42_energy_grid_energy_emission_factor
  name: I.4.2 Energy Grid Energy Emission Factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energitrager, scope]
  output_dimensions: [ghg, energitrager, scope]
  params:
    gpc_sector: I.4.2
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: i42_energy_grid_energy_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energitrager
    - id: scope

- id: ii11_onroad_transport_fuel_consumption
  name: II.1.1 On-Road Transport Fuel Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energitrager, scope]
  output_dimensions: [energitrager, scope]
  params:
    gpc_sector: II.1.1
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: ii11_onroad_transport_fuel_consumption_emissions
    to_dimensions:
    - id: energitrager
    - id: scope

- id: ii11_onroad_transport_fuel_consumption_emissions
  name: II.1.1 On-Road Transport Fuel Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: ii11_onroad_transport_fuel_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: ii11_onroad_transport_fuel_emission_factor
  name: II.1.1 On-Road Transport Fuel Emission Factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energitrager, scope]
  output_dimensions: [ghg, energitrager, scope]
  params:
    gpc_sector: II.1.1
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: ii11_onroad_transport_fuel_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energitrager
    - id: scope

- id: ii12_onroad_transport_grid_energy_consumption
  name: II.1.2 On-Road Transport Grid Energy Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: MWh/a
  input_dimensions: [energitrager, scope]
  output_dimensions: [energitrager, scope]
  params:
    gpc_sector: II.1.2
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: ii12_onroad_transport_grid_energy_consumption_emissions
    to_dimensions:
    - id: energitrager
    - id: scope

- id: ii12_onroad_transport_grid_energy_consumption_emissions
  name: II.1.2 On-Road Transport Grid Energy Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: ii12_onroad_transport_grid_energy_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: ii12_onroad_transport_grid_energy_emission_factor
  name: II.1.2 On-Road Transport Grid Energy Emission Factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/MWh
  input_dimensions: [ghg, energitrager, scope]
  output_dimensions: [ghg, energitrager, scope]
  params:
    gpc_sector: II.1.2
  input_datasets:
  - id: gpc/potsdam
  output_nodes:
  - id: ii12_onroad_transport_grid_energy_consumption_emissions
    to_dimensions:
    - id: ghg
    - id: energitrager
    - id: scope

- id: i11_residential_fuel_total_emissions
  name: I.1.1 Residential Fuel Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i1_residential_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i12_residential_grid_energy_total_emissions
  name: I.1.2 Residential Grid Energy Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i1_residential_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i1_residential_total_emissions
  name: I.1 Residential Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i_stationary_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i42_energy_grid_energy_total_emissions
  name: I.4.2 Energy Grid Energy Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i4_energy_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i4_energy_total_emissions
  name: I.4 Energy Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: i_stationary_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: i_stationary_total_emissions
  name: I Stationary Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: net_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: ii11_onroad_transport_fuel_total_emissions
  name: II.1.1 On-Road Transport Fuel Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: ii1_onroad_transport_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: ii12_onroad_transport_grid_energy_total_emissions
  name: II.1.2 On-Road Transport Grid Energy Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: ii1_onroad_transport_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: ii1_onroad_transport_total_emissions
  name: II.1 On-Road Transport Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: ii_transportation_total_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

- id: ii_transportation_total_emissions
  name: II Transportation Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [energitrager, scope, ghg]
  output_dimensions: [energitrager, scope, ghg]
  output_nodes:
  - id: net_emissions
    to_dimensions:
    - id: energitrager
    - id: scope
    - id: ghg

#actions:

#- id: masterplan
#  name: All actions as a part of masterplan
#  type: gpc.DatasetAction
#  quantity: energy
#  unit: MWh/a
#  input_datasets:
#  - id: gpc/potsdam_master_plan_actions
#    forecast_from: 2022
##    filters:
##    - dimension: sector
##      categories: [I.1.1]
#  output_dimensions: [energitrager, scope]
##  input_dataset_processors: [LinearInterpolation]
#  params:
#  - id: gpc_sector
#    value: I.1.1

pages:
- id: home
  name: Potsdam BASIC+ Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Potsdam Zielwerte Masterplan
  lead_paragraph: GPC BASIC+ greenhouse gas inventory (1995-2022) and forecast (2023-2050)
    for the City of Potsdam.

scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Action Plan
  all_actions_enabled: true
