id: saskatoon_gpc
default_language: en
supported_languages: []
site_url: https://saskatoon-basic.paths.staging.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 2261c6af56a12ae4d2c5118c6b8465363ed49840
  dvc_remote: kausal-s3
name: Saskatoon BASIC Greenhouse Gas Inventory
owner_en: City of Saskatoon
theme_identifier: ca-saskatoon
target_year: 2021
model_end_year: 2021
minimum_historical_year: 2014
maximum_historical_year: 2021
emission_unit: t/a
emission_forecast_from: 2022
emission_dimensions: [scope, ghg]
# normalizations:
# - normalizer_node: population
#   quantities:
#   - id: emissions
#     unit: t/cap/a
#   - id: energy
#     unit: kWh/cap/a
#   - id: mileage
#     unit: miles/cap/a
features:
  baseline_visible_in_graphs: true


dimensions:
- id: company
  label: Company
  categories:
  - id: saskenergy
    label: SaskEnergy
  - id: saskpower
    label: SaskPower
  - id: slp
    label: SL&P

- id: energy_carrier
  label: Energy Carrier
  categories:
  - id: aviation_gasoline
    label: Aviation Gasoline
  - id: diesel
    label: Diesel
  - id: district_heat
    label: District Heat
  - id: electricity
    label: Electricity
  - id: fuel_oil
    label: Fuel Oil
  - id: gasoline
    label: Gasoline
  - id: kerosene
    label: Kerosene
  - id: natural_gas
    label: Natural Gas
  - id: propane
    label: Propane

- id: ghg
  label: Greenhouse Gas
  categories:
  - id: co2e
    label: CO2 Equivalent
  - id: co2
    label: CO2
  - id: ch4
    label: CH4
  - id: n2o
    label: N2O

- id: scope
  label: Emissions Scope
  categories:
  - id: scope1
    label: Scope 1
  - id: scope2
    label: Scope 2
  - id: scope3
    label: Scope 3

- id: vehicle_type
  label: Vehicle Type
  categories:
  - id: light_duty
    label: Light-Duty
  - id: heavy_duty
    label: Heavy-Duty


emission_sectors:
- id: net_emissions
  name: GPC BASIC Greenhouse Gas Emissions
  is_outcome: true

# - id: i_emissions
#   name: I Stationary Emissions
#   part_of: net_emissions

# - id: ii_emissions
#   name: II Transportation Emissions
#   part_of: net_emissions


nodes:
- id: i12_consumption
  name: I.1.2 Residential Grid Energy Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: kWh/a
  input_dimensions: [scope, energy_carrier, company]
  output_dimensions: [scope, energy_carrier, company]
  params:
    gpc_sector: I.1.2
  input_datasets:
  - id: gpc/saskatoon
  output_nodes:
  - id: i12_consumption_emissions
    to_dimensions:
    - id: scope
    - id: energy_carrier
    - id: company

- id: i12_factors
  name: I.1.2 Residential Grid Energy Emission Factors
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/kWh
  input_dimensions: [scope, energy_carrier, ghg]
  output_dimensions: [scope, energy_carrier, ghg]
  params:
    gpc_sector: I.1.2
  input_datasets:
  - id: gpc/saskatoon
  output_nodes:
  - id: i12_consumption_emissions
    to_dimensions:
    - id: scope
    - id: energy_carrier
    - id: ghg

- id: i12_consumption_emissions
  name: I.1.2 Residential Grid Energy Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, company, ghg]
  output_dimensions: [scope, energy_carrier, company, ghg]
  output_nodes:
  - id: i12_total_emissions

- id: i12_total_emissions
  name: I.1.2 Residential Grid Energy Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, company, ghg]
  output_dimensions: [scope, energy_carrier, company, ghg]
  output_nodes:
  - id: i1_emissions



- id: i1_emissions
  name: I.1 Residential Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, company, ghg]
  output_dimensions: [scope, energy_carrier, company, ghg]
  output_nodes:
  - id: i_emissions
    from_dimensions:
    - id: company
      flatten: true



- id: i21_consumption
  name: I.2.1 Commercial & Institutional Fuel Combustion
  type: gpc.DatasetNode
  quantity: fuel_consumption
  unit: m**3/a
  input_dimensions: [scope, energy_carrier]
  output_dimensions: [scope, energy_carrier]
  params:
    gpc_sector: I.2.1
  input_datasets:
  - id: gpc/saskatoon
  output_nodes:
  - id: i21_consumption_emissions
    to_dimensions:
    - id: scope
    - id: energy_carrier

- id: i21_factors
  name: I.2.1 Commercial & Institutional Fuel Emission Factors
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/m**3
  input_dimensions: [scope, energy_carrier, ghg]
  output_dimensions: [scope, energy_carrier, ghg]
  params:
    gpc_sector: I.2.1
  input_datasets:
  - id: gpc/saskatoon
  output_nodes:
  - id: i21_consumption_emissions
    to_dimensions:
    - id: scope
    - id: energy_carrier
    - id: ghg

- id: i21_consumption_emissions
  name: I.2.1 Commercial & Institutional Fuel Combustion Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, ghg]
  output_dimensions: [scope, energy_carrier, ghg]
  output_nodes:
  - id: i21_total_emissions

- id: i21_total_emissions
  name: I.2.1 Commercial & Institutional Fuel Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, ghg]
  output_dimensions: [scope, energy_carrier, ghg]
  output_nodes:
  - id: i2_emissions



- id: i2_emissions
  name: I.2 Commercial & Institutional Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, ghg]
  output_dimensions: [scope, energy_carrier, ghg]
  output_nodes:
  - id: i_emissions



- id: i_emissions
  name: I Stationary Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, energy_carrier, ghg]
  output_dimensions: [scope, energy_carrier, ghg]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: energy_carrier
      flatten: true



- id: ii21_emissions
  name: II.2.1 Railway Fuel Emissions
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  input_dimensions: [scope, ghg]
  output_dimensions: [scope, ghg]
  params:
    gpc_sector: II.2.1
  input_datasets:
  - id: gpc/saskatoon
  output_nodes:
  - id: net_emissions


pages:
- id: home
  name: Saskatoon BASIC Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Climate-4-CAST Project
  lead_paragraph: GPC BASIC greenhouse gas inventory (2014-2021) for the City of Saskatoon.

scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Action Initiatives
  all_actions_enabled: true
