id: surrey
default_language: en
supported_languages: []
site_url: https://surrey.paths-test.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: a66ed46fef746e41c3cc838c2defea6c0cf27ace
  dvc_remote: kausal-s3
  default_path: surrey
name: Surrey Greenhouse Gas Inventory
owner_en: City of Surrey
theme_identifier: ca-surrey
target_year: 2018
model_end_year: 2018
# reference_year: 2007
minimum_historical_year: 2007
maximum_historical_year: 2018
emission_unit: t/a
emission_forecast_from: 2019
emission_dimensions: []
emission_dataset: surrey/greenhouse_gas_emissions
emission_sector_dimension: emission_sectors
normalizations:
- normalizer_node: population
  quantities:
  - id: emissions
    unit: t/cap/a
  - id: energy
    unit: kWh/cap/a
features:
  baseline_visible_in_graphs: false


action_groups:
- id: buildings
  name: Buildings
- id: transportation
  name: Transportation
- id: electric_grid
  name: Electric Grid
- id: solid_waste
  name: Solid Waste


dimensions:
- id: emission_sector
  label: Emission Sector
  categories:
  - id: residential
    label: Residential Buildings
  - id: ici_buildings
    label: ICI Buildings

  - id: ici_equipment
    label: ICI Equipment
  - id: construction
    label: Construction Equipment
  - id: industrial
    label: Industrial Equipment
  - id: agricultural
    label: Agricultural Equipment
  - id: lawn_garden
    label: Lawn & Garden Equipment
  - id: recreation
    label: Recreation Equipment

  - id: waste
    label: Waste
  - id: fugitive
    label: Fugitive
  - id: waste_water
    label: Waste Water Treatment
  - id: district
    label: District Energy

- id: vehicle_type
  label: Vehicle Type
  categories:
  - id: ldv
    label: Light-Duty Vehicles
  - id: hdv
    label: Heavy-Duty Vehicles
  - id: rail
    label: Rail Locomotives

- id: greenhouse_gas
  label: Greenhouse Gas
  categories:
  - id: co2_eq
    label: CO2 Equivalent
  - id: co2
    label: CO2
  - id: ch4
    label: CH4
  - id: n2o
    label: N2O

- id: energy_carrier
  label: Energy Carrier
  categories:
  - id: electricity
    label: Electricity
  - id: natural_gas
    label: Natural Gas
  - id: combined_fuels
    label: Combined Fuels


params:
- id: municipality_name
  value: surrey


emission_sectors:
- id: net_emissions
  name: Greenhouse Gas Emissions
  minimum_year: 2007
  is_outcome: true
  description: <p>Greenhouse Gas Emissions</p><p><b>Unit:</b> t/yr. = metric tons
    CO2e per year</b></p>

- id: waste_emissions
  name: Waste Emissions
  color: '#C4D652'
  category: waste
  part_of: net_emissions
  input_dataset_processors: [LinearInterpolation]

- id: other_emissions
  name: Other Emissions
  color: '#D6E287'
  part_of: net_emissions
  input_dataset_processors: [LinearInterpolation]

- id: waste_water_emissions
  name: Waste Water Treatment
  category: waste_water
  part_of: other_emissions
  input_dataset_processors: [LinearInterpolation]

- id: district_emissions
  name: District Energy
  category: district
  part_of: other_emissions
  input_dataset_processors: [LinearInterpolation]


nodes:
# ----- Population -----

- id: population
  name: Population
  type: simple.AdditiveNode
  quantity: population
  unit: cap
  input_dimensions: []
  output_dimensions: []
  input_datasets:
  - id: surrey/population
  input_dataset_processors: [LinearInterpolation]

# ----- Building Emissions -----

- id: stationary_energy_consumption
  name: Stationary Energy Consumption
  type: simple.AdditiveNode
  quantity: energy
  unit: kWh/a
  input_dimensions: [emission_sector, energy_carrier]
  output_dimensions: [emission_sector, energy_carrier]
  input_datasets:
  - id: surrey/stationary_energy_consumption
  input_dataset_processors: [LinearInterpolation]

- id: energy_emission_factors
  name: Electricity & Natural Gas Emission Factors
  type: simple.AdditiveNode
  quantity: emission_factor
  unit: kg/kWh
  input_dimensions: [energy_carrier]
  output_dimensions: [energy_carrier]
  input_datasets:
  - id: surrey/energy_emission_factors
  input_dataset_processors: [LinearInterpolation]

- id: stationary_emissions
  name: Stationary (Buildings)
  type: simple.MultiplicativeNode
  color: '#6EC0C7'
  quantity: emissions
  unit: t/a
  input_dimensions: [emission_sector, energy_carrier]
  output_dimensions: [emission_sector, energy_carrier]
  input_nodes:
  - id: stationary_energy_consumption
    tags: [non_additive]
  - id: energy_emission_factors
    tags: [non_additive]
    to_dimensions:
    - id: energy_carrier
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: emission_sector
      flatten: true
    - id: energy_carrier
      flatten: true

# ----- Other Stationary Emissions -----

- id: stationary_emission_factors
  name: Per Capita Stationary+ Emission Factors
  type: simple.AdditiveNode
  quantity: emission_factor
  unit: kg/cap/a
  input_dimensions: [emission_sector]
  output_dimensions: [emission_sector]
  input_datasets:
  - id: surrey/stationary_emission_factors
  input_dataset_processors: [LinearInterpolation]
  minimum_year: 2016

- id: stationary_plus_emissions_pc
  name: Per Capita Stationary+ Emissions (Engines & Equipment)
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [emission_sector]
  output_dimensions: [emission_sector]
  input_nodes:
  - id: population
    to_dimensions: []
  - id: stationary_emission_factors

- id: stationary_plus_emissions
  name: Stationary+ (Engines & Equipment)
  type: simple.AdditiveNode
  color: '#A7D6DB'
  quantity: emissions
  unit: t/a
  input_dimensions: [emission_sector, energy_carrier]
  output_dimensions: [emission_sector, energy_carrier]
  input_datasets:
  - id: surrey/stationary_emissions
  input_dataset_processors: [LinearInterpolation]
  input_nodes:
  - id: stationary_plus_emissions_pc
    to_dimensions:
    - id: emission_sector
    - id: energy_carrier
      categories: [combined_fuels]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: emission_sector
      flatten: true
    - id: energy_carrier
      flatten: true
  minimum_year: 2007

# ----- Transportation Emissions

- id: transportation_emission_factors
  name: Per Capita Transportation(+) Emission Factors
  type: simple.AdditiveNode
  quantity: emission_factor
  unit: kg/cap/a
  input_dimensions: [vehicle_type]
  output_dimensions: [vehicle_type]
  input_datasets:
  - id: surrey/transportation_emission_factors
  input_dataset_processors: [LinearInterpolation]
  minimum_year: 2016

- id: transportation_emissions_pc
  name: Per Capita Transportation(+) Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [vehicle_type]
  output_dimensions: [vehicle_type]
  input_nodes:
  - id: population
    to_dimensions: []
  - id: transportation_emission_factors
  minimum_year: 2016

- id: transportation_emissions
  name: Transportation (On-Road)
  type: simple.AdditiveNode
  color: '#B93F40'
  quantity: emissions
  unit: t/a
  input_dimensions: [vehicle_type]
  output_dimensions: [vehicle_type]
  input_datasets:
  - id: surrey/transportation_emissions
    filters:
    - dimension: vehicle_type
      categories: [ldv, hdv]
  input_dataset_processors: [LinearInterpolation]
  input_nodes:
  - id: transportation_emissions_pc
    from_dimensions:
    - id: vehicle_type
      categories: [ldv, hdv]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: vehicle_type
      flatten: true
  minimum_year: 2007

- id: transportation_plus_emissions
  name: Transportation+ (Rail)
  type: simple.AdditiveNode
  color: '#E06565'
  quantity: emissions
  unit: t/a
  input_dimensions: [vehicle_type]
  output_dimensions: [vehicle_type]
  input_datasets:
  - id: surrey/transportation_emissions
    filters:
    - dimension: vehicle_type
      categories: [rail]
  input_dataset_processors: [LinearInterpolation]
  input_nodes:
  - id: transportation_emissions_pc
    from_dimensions:
    - id: vehicle_type
      categories: [rail]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: vehicle_type
      flatten: true
  minimum_year: 2007


pages:
- id: home
  name: Surrey Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title_en: Development Version
  lead_paragraph_en: <p>The City of Surrey's greenhouse gas inventory (2007-2018)</p>


scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Change Action Strategy
  all_actions_enabled: true
