instance:
  id: tampere
  default_language: fi
  dataset_repo: https://github.com/kausaltech/dvctest.git
  name: Hiilineutraali Tampere 2030
  target_year: 2030
  emission_dataset: tampere/scenarios/emissions/bau
  emission_unit: kt
  emission_forecast_from: 2019
  parameters:
    - id: municipality_name
      value: Tampere
  emission_sectors:
    - id: net_emissions
      name: Kokonaispäästöt (scope 2)
      name_en: Net emissions (scope 2)

    - id: transportation_emissions
      name: Liikenteen päästöt
      name_en: Transportation
      part_of: net_emissions
      color: '#668EC9'
    - id: car_emissions
      name: Henkilöautot
      name_en: Private cars
      column: Private cars
      part_of: transportation_emissions
    - id: van_emissions
      name: Pakettiautot
      name_en: Vans
      column: Vans
      part_of: transportation_emissions
    - id: bus_emissions
      name: Linja-autot
      name_en: Buses
      column: Buses
      part_of: transportation_emissions
    - id: truck_emissions
      name: Kuorma-autot
      name_en: Trucks and lorries
      column: Trucks and lorries
      part_of: transportation_emissions
    - id: motorbike_emissions
      name: Moottoripyörät yms.
      name_en: Motorbikes etc.
      column: Motorbikes
      part_of: transportation_emissions
    - id: local_train_emissions
      name: Lähijunat
      name_en: Local trains
      column: Local trains
      part_of: transportation_emissions
    - id: tram_emissions
      name: Raitiotiet
      name_en: Trams
      column: Trams
      part_of: transportation_emissions

    #
    # Heating
    #
    - id: building_heating_emissions
      name: Rakennusten lämmityksen päästöt
      name_en: Building heating
      part_of: net_emissions
      color: '#AD3963'

    #- id: district_heating_emissions
    #  name: Kaukolämpö
    #  part_of: building_heating_emissions
    #  column: District heating

    - id: separate_heating_emissions
      name: Erillislämmitys
      name_en: Separate heating
      part_of: building_heating_emissions
    - id: gas_heating_emissions
      part_of: separate_heating_emissions
      name: Kaasulämmitys
      name_en: Gas heating
      column: Gas heating

    - id: electric_heating_emissions
      name: Sähkölämmitys
      name_en: Electric heating
      part_of: building_heating_emissions

    - id: industry_emissions
      name: Teollisuuden ja työkoneiden päästöt
      name_en: Industry and machinery
      part_of: net_emissions
      column: Industry and machinery
      color: '#E8B455'

    - id: waste_treatment_emissions
      name: Jätehuollon päästöt
      name_en: Waste treatment
      part_of: net_emissions
      color: '#397368'

    - id: solid_waste_treatment_emissions
      name: Kiinteän jätteen käsittelyn päästöt
      name_en: Solid waste treatment
      column: Solid waste treatment
      part_of: waste_treatment_emissions

    - id: waste_water_treatment_emissions
      name: Jäteveden puhdistuksen päästöt
      name_en: Waste water treatment
      column: Waste water treatment
      part_of: waste_treatment_emissions

    - id: agriculture_emissions
      name_en: Agriculture
      name: Maatalouden päästöt
      part_of: net_emissions
      color: '#ABC872'

    - id: cattle_digestion_emissions
      name_en: Cattle digestion
      name: Eläinten ruoansulatus
      part_of: agriculture_emissions
      column: Cattle digestion

    - id: manure_treatment_emissions
      name_en: Manure treatment
      name: Lannankäsittely
      part_of: agriculture_emissions
      column: Manure treatment

    - id: field_crops_emissions
      name_en: Field crops
      name: Peltoviljelyn päästöt
      part_of: agriculture_emissions
      column: Field crops

    - id: industrial_electricity_consumption_emissions
      name_en: Industrial electricity consumption
      name: Teollisuuden sähkön kulutuksen päästöt
      part_of: electricity_consumption_emissions
      column: Industrial electricity consumption

  nodes:
    - id: population
      type: finland.Population
      name: Väestö

    - id: district_heating_emissions
      name: Kaukolämpö
      name_en: District heating emissions
      type: simple.EmissionFactorActivity
      unit: kt
      quantity: emissions
      output_nodes:
        - building_heating_emissions

    - id: district_heating_consumption
      name: Kaukolämmön kulutus
      name_en: District heat consumption
      unit: GWh
      quantity: energy
      type: simple.Activity
      output_nodes:
        - district_heating_emissions
      historical_values: [[1990, 1388.4], [2010, 2206.6], [2011, 1869.3], [2012, 2072.7], [2013, 1888.2], [2014, 1872.2], [2015, 1775.6], [2016, 1956.7], [2017, 1917.2], [2018, 1955.1]]
      forecast_values: [[2019, 1911], [2020, 1840], [2021, 1815], [2022, 1791], [2023, 1766], [2024, 1741], [2025, 1716], [2026, 1691], [2027, 1666], [2028, 1641], [2029, 1617], [2030, 1592]]

    - id: district_heating_emission_factor
      name: Kaukolämmön päästökerroin
      name_en: District heating emission factor
      type: simple.AdditiveNode
      unit: g/kWh
      quantity: emission_factor
      output_nodes:
        - district_heating_emissions
      historical_values: [[1990, 250], [2010, 179], [2011, 170.1], [2012, 162.3], [2013, 153.9], [2014, 160.6], [2015, 140.7], [2016, 140], [2017, 130], [2018, 136.3]]
      forecast_values: [[2019, 126], [2020, 123], [2021, 123], [2022, 123], [2023, 123], [2024, 123], [2025, 123], [2026, 123], [2027, 123], [2028, 123], [2029, 123], [2030, 123]]

    - id: oil_heating_emissions
      type: simple.EmissionFactorActivity
      unit: kt
      quantity: emissions
      name: Öljylämmitys
      name_en: Oil heating
      output_nodes:
        - separate_heating_emissions

    - id: oil_heating_energy_use
      unit: GWh
      quantity: energy
      type: simple.Activity
      name: Öljylämmityksen energiankulutus
      name_en: Oil heating energy consumption
      output_nodes:
        - oil_heating_emissions
      historical_values: [[2010, 332.3], [2011, 266.0], [2012, 298.9], [2013, 275.6], [2014, 276.4], [2015, 264.7], [2016, 297.0], [2017, 280.4], [2018, 274.1]]
      forecast_values: [[2019, 263.2], [2020, 252.3], [2021, 241.4], [2022, 230.5], [2023, 219.6], [2024, 208.7], [2025, 197.8], [2026, 186.9], [2027, 176.0], [2028, 165.1], [2029, 154.2], [2030, 143.3]]

    - id: oil_heating_emission_factor
      type: simple.AdditiveNode
      unit: g/kWh
      quantity: emission_factor
      name: Lämmitysöljyn päästökerroin
      name_en: Heating oil emission factor
      historical_values: [[2010, 268.4], [2011, 263.5], [2012, 263.5], [2013, 263.5], [2014, 264.5], [2015, 264.5], [2016, 266.3], [2017, 268], [2018, 268], [2019, 268], [2020, 268]]
      forecast_values: [[2021, 264.1055], [2022, 260.211], [2023, 256.3165], [2024, 252.422], [2025, 248.5275], [2026, 244.633], [2027, 240.7385], [2028, 236.844], [2029, 236.844], [2030, 236.844]]
      output_nodes:
        - oil_heating_emissions

      #
      # ----------- geothermal --------------
      #
    - id: geothermal_heating_emissions
      type: simple.EmissionFactorActivity
      unit: kt
      quantity: emissions
      name: Maalämmön päästöt
      name_en: Geothermal heating emissions
      input_nodes:
        - electricity_production_emission_factor
      output_nodes:
        - electric_heating_emissions

    - id: geothermal_heating_electricity_use
      unit: GWh
      quantity: energy
      type: simple.Activity
      name: Maalämmön sähkönkulutus
      name_en: Geothermal heating electricity consumption
      output_nodes:
        - geothermal_heating_emissions
      historical_values: [[1990, 0], [2010, 2.8], [2011, 4.5], [2012, 5.3], [2013, 7.6], [2014, 7.6], [2015, 8.1], [2016, 10.3], [2017, 13.7], [2018, 16.3]]
      forecast_values: [[2019, 18.5], [2020, 20.6], [2021, 22.8], [2022, 24.9], [2023, 27.1], [2024, 29.2], [2025, 31.4], [2026, 33.5], [2027, 35.7], [2028, 37.8], [2029, 40.0], [2030, 42.1]]


    - id: direct_electric_heating_emissions
      type: simple.EmissionFactorActivity
      unit: kt
      quantity: emissions
      name: Suorasähkölämmityksen päästöt
      name_en: Direct electric heating emissions
      input_nodes:
        - electricity_production_emission_factor
      output_nodes:
        - electric_heating_emissions

    - id: direct_electric_heating_electricity_use
      quantity: energy
      type: simple.Activity
      unit: GWh
      name: Suorasähkölämmityksen sähkönkulutus
      name_en: Direct electric heating electricity consumption
      output_nodes:
        - direct_electric_heating_emissions
      historical_values: [[1990, 112.8], [2010, 217], [2011, 207], [2012, 215], [2013, 208], [2014, 201], [2015, 195], [2016, 216.5], [2017, 215.8], [2018, 218.3], [2019, 215.8]]
      forecast_values: [[2020, 210], [2021, 210], [2022, 210], [2023, 210], [2024, 210], [2025, 210], [2026, 211], [2027, 211], [2028, 211], [2029, 211], [2030, 211]]

      #
      # ----------- Electricity use ------------
      #
    - id: other_electricity_consumption_per_capita
      name: Sähkönkulutus asukasta kohti
      name_en: Electricity consumption per capita
      type: simple.AdditiveNode
      unit: kWh/person
      output_nodes:
        - other_electricity_consumption
      historical_values: [[1990, 2211], [2010, 5728], [2011, 5555], [2012, 5672], [2013, 5531], [2014, 5550], [2015, 5423], [2016, 5477], [2017, 5467], [2018, 5328]]
      forecast_values: [[2019, 5289], [2020, 5249], [2021, 5210], [2022, 5171], [2023, 5131], [2024, 5092], [2025, 5052], [2026, 5013], [2027, 4974], [2028, 4934], [2029, 4895], [2030, 4855]]

    - id: other_electricity_consumption
      name: Muu sähkönkulutus
      name_en: Other electricity consumption
      type: simple.PerCapitaActivity
      unit: GWh
      quantity: energy
      input_nodes:
        - population
      output_nodes:
        - other_electricity_consumption_emissions

    - id: other_electricity_consumption_emissions
      name: Muun sähkönkulutuksen päästöt
      name_en: Other electricity consumption emissions
      type: simple.EmissionFactorActivity
      unit: kt
      input_nodes:
        - electricity_production_emission_factor
      output_nodes:
        - electricity_consumption_emissions

    - id: electricity_production_emission_factor
      name: Sähköntuotannon päästökerroin
      name_en: Electricity production emission factor
      type: simple.AdditiveNode
      unit: g/kWh
      quantity: emission_factor
      historical_values: [[1990, 350], [2010, 247], [2011, 200], [2012, 132], [2013, 160], [2014, 131], [2015, 104], [2016, 109], [2017, 95], [2018, 109], [2019, 92]]
      forecast_values: [[2020, 87], [2021, 81], [2022, 76], [2023, 70], [2024, 65], [2025, 59], [2026, 54], [2027, 48], [2028, 43], [2029, 37], [2030, 31]]

    - id: electricity_consumption_emissions
      name: Sähkön kulutuksen päästöt
      name_en: Electricity consumption emissions
      type: simple.SectorEmissions
      unit: kt
      color: '#F4D240'
      output_nodes:
        - net_emissions

    - id: renewable_electricity_production
      name: Uusiutuva sähköntuotanto
      name_en: Renewable electricity production
      type: simple.AdditiveNode
      unit: GWh
      quantity: energy
      output_nodes:
        - renewable_electricity_production_emissions_reductions

    - id: renewable_electricity_production_emissions_reductions
      name: Uusiutuvan sähköntuotannon päästövähennykset
      name_en: Renewable electricity production emissions reductions
      type: simple.EmissionFactorActivity
      unit: kt
      input_nodes:
        - electricity_production_emission_factor
      output_nodes:
        - electricity_consumption_emissions

  actions:
    # - id: reduce_heating_emissions
    #   name: Vähennetään lämmityksen päästöjä
    #   type: simple.EmissionReductionAction
    #   output_nodes:
    #     - building_heating_emissions
    #   input_datasets:
    #     - id: tampere/scenarios/diff
    #       column: Heating total

    - id: naistenlahti3
      name: Naistenlahti 3 -biovoimalaitos
      name_en: Naistenlahti 3 bio thermal plant
      type: simple.CumulativeAdditiveAction
      output_nodes:
        - district_heating_emission_factor
      forecast_values: [[2022, -23], [2023, -23]]
      unit: g/kWh

    - id: other_renewable_district_heating
      name: Kaukolämmön tuotannossa lisätään uusiutuvaa energiaa
      name_en: Increase share of renewables in district heat production
      type: simple.CumulativeAdditiveAction
      output_nodes:
        - district_heating_emission_factor
      forecast_values: [[2024, -8], [2025, -16], [2026, -4], [2027, -4], [2028, -7], [2029, -14], [2030, -6]]
      unit: g/kWh

    - id: private_building_energy_renovation
      name: Korjausrakentaminen yksityisissä kiinteistöissä
      name_en: Energy renovation of privately owned buildings
      type: simple.LinearCumulativeAdditiveAction
      output_nodes:
        - district_heating_consumption
        - other_electricity_consumption
        - direct_electric_heating_electricity_use
      forecast_values:
        - id: district_heating_consumption
          values: [[2020, 0], [2030, -239]]
        - id: other_electricity_consumption
          values: [[2020, 0], [2030, -12.65]]
        - id: direct_electric_heating_electricity_use
          values: [[2020, 0], [2030, 10.01]]
      unit: GWh

    - id: distributed_renewable_energy
      name: Hajautettu uusiutuva energia
      name_en: Distributed renewable energy production
      description: Arvioitu aurinkosähkön tuotannon kasvu. Sähkölaitos arvioi, että vuonna 2030 tuotanto olisi noin 10 - 20 GWh/vuosi. Nykytuotanto 2020 on noin 0,2 GWh. 2016 tehdyn uusiutuvan energian kuntakatselmuksen mukaan käyttämätön kokonaispotentiaali rakennusten katoilla on 800-900 GWh (ei huomioi kaikkia rajoitteita)
      type: simple.CumulativeAdditiveAction
      output_nodes:
        - renewable_electricity_production
      forecast_values: [[2020, -0.2], [2021, -0.3], [2022, -0.45], [2023, -0.6], [2024, -0.8], [2025, -1.1], [2026, -1.5], [2027, -2], [2028, -2.7], [2029, -3.3], [2030, -4]]
      allowed_params:
        - id: target_year_ratio
          min_value: 0
          max_value: 5
          description: Prosentuaalinen lisäys uusiutuvan energian tuotannossa
          description_en: Increase in renewable energy production
      unit: GWh

    - id: oil_heated_private_buildings_to_geothermal
      name: Öljylämmityksestä luopuminen yksityisessä rakenuskannassa
      name_en: Private oil heated buildings to geothermal
      type: simple.CumulativeAdditiveAction
      output_nodes:
        - oil_heating_energy_use
        - geothermal_heating_electricity_use
      forecast_values:
        - id: oil_heating_energy_use
          values: [[2021, -5.73], [2022, -5.73], [2023, -5.73], [2024, -5.73], [2025, -5.73], [2026, -5.73], [2027, -5.73], [2028, -5.73], [2029, -5.73], [2030, -5.73]]
        - id: geothermal_heating_electricity_use
          values: [[2021, 2.10], [2022, 2.10], [2023, 2.10], [2024, 2.10], [2025, 2.10], [2026, 2.10], [2027, 2.10], [2028, 2.10], [2029, 2.10], [2030, 2.10]]
      unit: GWh
      description: Yksityiset kiinteistöt vaihtavat öljylämmityksen maalämpöön. 95 % tarvittavasta lämmöstä tuotetaan COP 3:lla, loput on suorasähköä. Perustuu Juho Rinta-Rahkon arvioon Tampereen korjausrakentamisen ja energianeuvonnan potentiaalista. Öljylämmitystä jää jäljelle palvelurakennuksiin ja teollisuusrakennuksiin.

    - id: oil_heated_municipal_buildings_to_heat_pump
      name: Öljylämmityksestä luopuminen kaupungin rakennuskannassa
      type: simple.LinearCumulativeAdditiveAction
      output_nodes:
        - oil_heating_energy_use
        - direct_electric_heating_electricity_use
      forecast_values:
        - id: oil_heating_energy_use
          values: [[2020, 0], [2025, -3.674]]
        - id: direct_electric_heating_electricity_use
          values: [[2020, 0], [2025, 1.468]]
      unit: GWh
      description: Kaupungin kiinteistöt kuluttavat lähtötilanteessa öljyä 367 378 l/v eli n. 3 674 MWh eli 3,67 GWh. Öljyä korvataan näillä näkymin VILPeillä, joiden COP on noin 2,5, kun ne tuottavat kaiken tarvittavan lämmön. Bioöljyä on ajateltu pidettävän varalla, mutta sen osuus energiankulutuksesta on merkityksetön.

  pages:
    - id: home
      name: Hiilineutraali Tampere 2030 -päästöskenaario
      path: '/'
      type: emission
      node: net_emissions

  scenarios:
    - id: baseline
      name: Peruskehitys
      name_en: Baseline
      params:
        - id: naistenlahti3.enabled
          value: true

    - id: roadmap
      default: true
      name: Hiilineutraali Tampere 2030 -tiekartta
      name_en: Carbon-neutral Tampere 2030 roadmap
      all_actions_enabled: true
