instance:
  id: tampere
  dataset_repo: https://github.com/kausaltech/dvctest.git
  name: Hiilineutraali Tampere 2030
  nodes:
    - id: net_emissions
      name: Kokonaispäästöt (scope 2)
      type: simple.SectorEmissions
    - id: transportation_emissions
      name: Liikenteen päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Transportation total
    - id: building_heating_emissions
      name: Rakennusten lämmityksen päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Heating total

  pages:
    - id: home
      path: '/'
      name: Kokonaispäästöt
      cards:
        - name: Kokonaispäästöt Tampereella
          type: stacked
          metrics:
            - id: net_emissions
              only_inputs: true

        - name: Liikenteen päästökehitys
          metrics:
            - id: transportation_emissions
          upstream_cards:
            - net_emissions

  scenarios:
    - id: baseline
      name: Peruskehitys
    - id: roadmap
      name: Hiilineutraali Tampere 2030 -tiekartta
      interventions:
        - id: reduce_building_heating_emissions
          name: Rakennusten lämmityksen päästöt putoavat
          type: yearly
          output_nodes:
            - building_heating_emissions
          values:
            - 2021: -8.1
            - 2022: -10.3
            - 2023: -13.6
            - 2030: -124.2
