instance:
  id: tampere
  dataset_repo: https://github.com/kausaltech/dvctest.git
  name: Hiilineutraali Tampere 2030
  target_year: 2030
  nodes:
    - id: net_emissions
      name: Kokonaispäästöt (scope 2)
      type: simple.SectorEmissions

    - id: transportation_emissions
      name: Liikenteen päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Transportation total

    - id: building_heating_emissions
      name: Rakennusten lämmityksen päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Heating total

    - id: electricity_consumption_emissions
      name: Sähkön kulutuksen päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Electricity consumption total

    - id: industry_emissions
      name: Teollisuuden ja työkoneiden päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Industry and machinery

    - id: waste_treatment_emissions
      name: Jätehuollon päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Waste treatment total

    - id: agriculture_emissions
      name: Maatalouden päästöt
      type: simple.SectorEmissions
      output_nodes:
        - net_emissions
      input_datasets:
        - id: tampere/scenarios/bau
          column: Agriculture total

  actions:
    - id: reduce_transportation_emissions
      name: Vähennetään liikenteen päästöjä
      type: simple.EmissionReductionAction
      output_nodes:
        - transportation_emissions
      input_datasets:
        - id: tampere/scenarios/actions
          column: Transportation total

  pages:
    - id: home
      path: '/'
      name: Kokonaispäästöt
      cards:
        - name: Kokonaispäästöt Tampereella
          type: stacked
          metrics:
            - id: net_emissions
              only_inputs: true

        - name: Liikenteen päästökehitys
          metrics:
            - id: transportation_emissions
          upstream_cards:
            - net_emissions

        - name: Lämmityksen päästökehitys
          metrics:
            - id: building_heating_emissions
          upstream_cards:
            - net_emissions

  scenarios:
    - id: baseline
      name: Peruskehitys

    - id: roadmap
      name: Hiilineutraali Tampere 2030 -tiekartta
      actions:
        - id: reduce_transportation_emissions
          enabled: true
