instance:
  id: tampere
  default_language: fi
  dataset_repo: https://github.com/kausaltech/dvctest.git
  name: Hiilineutraali Tampere 2030
  target_year: 2030
  emission_dataset: tampere/scenarios/bau
  emission_unit: kt
  parameters:
    - id: municipality_name
      value: Tampere
  emission_sectors:
    - id: net_emissions
      name: Kokonaispäästöt (scope 2)
      name_en: Net emissions (scope 2)

    - id: transportation_emissions
      name: Liikenteen päästöt
      name_en: Transportation
      part_of: net_emissions
      color: '#668EC9'
    - id: car_emissions
      name: Henkilöautot
      name_en: Private cars
      column: Private cars
      part_of: transportation_emissions
    - id: van_emissions
      name: Pakettiautot
      name_en: Vans
      column: Vans
      part_of: transportation_emissions
    - id: bus_emissions
      name: Linja-autot
      name_en: Buses
      column: Buses
      part_of: transportation_emissions
    - id: truck_emissions
      name: Kuorma-autot
      name_en: Trucks and lorries
      column: Trucks and lorries
      part_of: transportation_emissions
    - id: motorbike_emissions
      name: Moottoripyörät yms.
      name_en: Motorbikes etc.
      column: Motorbikes
      part_of: transportation_emissions
    - id: local_train_emissions
      name: Lähijunat
      name_en: Local trains
      column: Local trains
      part_of: transportation_emissions
    - id: tram_emissions
      name: Raitiotiet
      name_en: Trams
      column: Trams
      part_of: transportation_emissions

    #
    # Heating
    #
    - id: building_heating_emissions
      name: Rakennusten lämmityksen päästöt
      name_en: Building heating
      part_of: net_emissions
      color: '#AD3963'

    #- id: district_heating_emissions
    #  name: Kaukolämpö
    #  part_of: building_heating_emissions
    #  column: District heating

    - id: separate_heating_emissions
      name: Erillislämmitys
      name_en: Separate heating
      part_of: building_heating_emissions
    - id: oil_heating_emissions
      name: Öljylämmitys
      name_en: Oil heating
      part_of: separate_heating_emissions
      column: Oil heating
    - id: gas_heating_emissions
      part_of: separate_heating_emissions
      name: Kaasulämmitys
      name_en: Gas heating
      column: Gas heating

    - id: electric_heating_emissions
      name: Sähkölämmitys
      name_en: Electric heating
      part_of: building_heating_emissions
    - id: geothermal_heating_emissions
      name: Maalämpö
      name_en: Geothermal heating
      part_of: electric_heating_emissions
      column: Geothermal heating
    - id: direct_electric_heating_emissions
      name: Suorasähkö
      name_en: Direct electric heating
      part_of: electric_heating_emissions
      column: Direct electric heating

    - id: industry_emissions
      name: Teollisuuden ja työkoneiden päästöt
      name_en: Industry and machinery
      part_of: net_emissions
      column: Industry and machinery
      color: '#E8B455'

    - id: waste_treatment_emissions
      name: Jätehuollon päästöt
      name_en: Waste treatment
      part_of: net_emissions
      color: '#397368'

    - id: solid_waste_treatment_emissions
      name: Kiinteän jätteen käsittelyn päästöt
      name_en: Solid waste treatment
      column: Solid waste treatment
      part_of: waste_treatment_emissions

    - id: waste_water_treatment_emissions
      name: Jäteveden puhdistuksen päästöt
      name_en: Waste water treatment
      column: Waste water treatment
      part_of: waste_treatment_emissions

    - id: agriculture_emissions
      name_en: Agriculture
      name: Maatalouden päästöt
      part_of: net_emissions
      color: '#ABC872'

    - id: cattle_digestion_emissions
      name_en: Cattle digestion
      name: Eläinten ruoansulatus
      part_of: agriculture_emissions
      column: Cattle digestion

    - id: manure_treatment_emissions
      name_en: Manure treatment
      name: Lannankäsittely
      part_of: agriculture_emissions
      column: Manure treatment

    - id: field_crops_emissions
      name_en: Field crops
      name: Peltoviljelyn päästöt
      part_of: agriculture_emissions
      column: Field crops

    - id: industrial_electricity_consumption_emissions
      name_en: Industrial electricity consumption
      name: Teollisuuden sähkön kulutuksen päästöt
      part_of: electricity_consumption_emissions
      column: Industrial electricity consumption

  nodes:
    - id: population
      type: finland.Population
      name: Väestö

    - id: district_heating_emissions
      name: Kaukolämpö
      name_en: District heating emissions
      type: simple.EmissionFactorActivity
      unit: kt
      quantity: emissions
      output_nodes:
        - building_heating_emissions

    - id: district_heating_consumption
      name: Kaukolämmön kulutus
      name_en: District heat consumption
      unit: GWh
      quantity: energy
      type: simple.Activity
      output_nodes:
        - district_heating_emissions
      historical_values: [[1990, 1388.4], [2010, 2206.6], [2011, 1869.3], [2012, 2072.7], [2013, 1888.2], [2014, 1872.2], [2015, 1775.6], [2016, 1956.7], [2017, 1917.2], [2018, 1955.1]]
      forecast_values: [[2019, 1911], [2020, 1840], [2021, 1815], [2022, 1791], [2023, 1766], [2024, 1741], [2025, 1716], [2026, 1691], [2027, 1666], [2028, 1641], [2029, 1617], [2030, 1592]]

    - id: district_heating_emission_factor
      name: Kaukolämmön päästökerroin
      name_en: District heating emission factor
      type: simple.AdditiveNode
      unit: g/kWh
      quantity: emission_factor
      output_nodes:
        - district_heating_emissions
      historical_values: [[1990, 250], [2010, 179], [2011, 170.1], [2012, 162.3], [2013, 153.9], [2014, 160.6], [2015, 140.7], [2016, 140], [2017, 130], [2018, 136.3]]
      forecast_values: [[2019, 126], [2020, 123], [2021, 123], [2022, 123], [2023, 123], [2024, 123], [2025, 123], [2026, 123], [2027, 123], [2028, 123], [2029, 123], [2030, 123]]

    - id: electricity_consumption_per_capita
      name: Sähkönkulutus asukasta kohti
      name_en: Electricity consumption per capita
      type: simple.AdditiveNode
      unit: kWh/person
      output_nodes:
        - electricity_consumption_other
      historical_values: [[2010, 5728], [2011, 5555], [2012, 5672], [2013, 5531], [2014, 5550], [2015, 5423], [2016, 5477], [2017, 5467], [2018, 5328]]
      forecast_values: [[2019, 5289], [2020, 5249], [2021, 5210], [2022, 5171], [2023, 5131], [2024, 5092], [2025, 5052], [2026, 5013], [2027, 4974], [2028, 4934], [2029, 4895], [2030, 4855]]

    - id: electricity_consumption_other
      name: Muu sähkönkulutus
      name_en: Other electricity consumption
      type: simple.PerCapita
      unit: GWh
      quantity: energy
      input_nodes:
        - population
      output_nodes:
        - electricity_consumption

    - id: electricity_consumption
      name: Sähkönkulutus
      name_en: Electricity consumption
      type: simple.AdditiveNode
      unit: GWh
      quantity: energy
      output_nodes:
        - electricity_consumption_emissions

    - id: electricity_production_emission_factor
      name: Sähköntuotannon päästökerroin
      name_en: Electricity production emission factor
      type: simple.AdditiveNode
      output_nodes:
        - electricity_consumption_emissions
      unit: g/kWh
      quantity: emission_factor
      historical_values: [[2010, 247], [2011, 200], [2012, 132], [2013, 160], [2014, 131], [2015, 104], [2016, 109], [2017, 95], [2018, 109], [2019, 92]]
      forecast_values: [[2020, 87], [2021, 81], [2022, 76], [2023, 70], [2024, 65], [2025, 59], [2026, 54], [2027, 48], [2028, 43], [2029, 37], [2030, 31]]

    - id: electricity_consumption_emissions
      name: Sähkön kulutuksen päästöt
      name_en: Electricity consumption
      type: simple.EmissionFactorActivity
      unit: kt
      color: '#F4D240'
      output_nodes:
        - net_emissions

  actions:
    # - id: reduce_heating_emissions
    #   name: Vähennetään lämmityksen päästöjä
    #   type: simple.EmissionReductionAction
    #   output_nodes:
    #     - building_heating_emissions
    #   input_datasets:
    #     - id: tampere/scenarios/diff
    #       column: Heating total

    - id: naistenlahti3
      name: Naistenlahti 3 -biovoimalaitos
      name_en: Naistenlahti 3 bio thermal plant
      type: simple.CumulativeAdditiveAction
      output_nodes:
        - district_heating_emission_factor
      forecast_values: [[2022, -23], [2023, -23]]
      unit: g/kWh

    - id: other_renewable_district_heating
      name: Kaukolämmön tuotannossa lisätään uusiutuvaa energiaa
      name_en: Increase share of renewables in district heat production
      type: simple.CumulativeAdditiveAction
      output_nodes:
        - district_heating_emission_factor
      forecast_values: [[2024, -8], [2025, -16], [2026, -4], [2027, -4], [2028, -7], [2029, -14], [2030, -6]]
      unit: g/kWh

  pages:
    - id: home
      name: Hiilineutraali Tampere 2030 -päästöskenaario
      path: '/'
      type: emission
      node: net_emissions

  scenarios:
    - id: baseline
      name: Peruskehitys

    - id: roadmap
      default: true
      name: Hiilineutraali Tampere 2030 -tiekartta
      actions:
        - id: naistenlahti3
          enabled: true
        - id: other_renewable_district_heating
          enabled: true
