instance:
  id: zuerich
  default_language: de-CH
  supported_languages: [en]
  site_url: https://zuerich.paths-test.kausal.tech
  dataset_repo:
    url: https://github.com/kausaltech/dvctest.git
    commit: af84a46c532a0d4d976767c6f4371601e9b41255
  name_en: Net Zero 2040
  name_de: Netto-Null 2040
  owner_en: City of Zürich
  owner_de: Stadt Zürich
  theme_identifier: zurich
  target_year: 2040
  reference_year: 1990
  minimum_historical_year: 2010
  maximum_historical_year: 2020
  emission_unit: t/inh/a
  emission_forecast_from: 2021
  params:

  emission_sectors:
  - id: direct_emissions
    name_en: Direct emissions
    name_de: Direkte Emissionen
    target_year_goal: 0
    is_outcome: true

    #
    # Buildings
    #
  - id: building_emissions
    name_en: Building emissions
    name_de: Gebäude
    part_of: direct_emissions
    color: '#e8404c'
    historical_values: [[1990, 2.96942], [2020, 1.71186]]
    input_dataset_processors: [LinearInterpolation]

    #
    # Transportation
    #
  - id: transportation_emissions
    name_en: Transportation emissions
    name_de: Mobilität
    part_of: direct_emissions
    color: '#0a8df6'
    historical_values: [[1990, 1.12260], [2020, 0.66457]]
    input_dataset_processors: [LinearInterpolation]

  - id: waste_treatment_emissions
    name_en: Waste disposal
    name_de: Entsorgung
    part_of: direct_emissions
    color: '#614600'
    historical_values: [[1990, 0.45001], [2020, 0.49011]]
    input_dataset_processors: [LinearInterpolation]

  - id: other_direct_emissions
    name_en: Other direct emissions
    name_de: Übrige direkte Emissionen
    part_of: direct_emissions

  - id: ippu_emissions
    name_en: Industrial and commercial process emissions
    name_de: Industrie- und Gewerbeprozesse
    part_of: other_direct_emissions
    color: '#ffcc00'
    historical_values: [[1990, 0.21308], [2020, 0.21308]]
    input_dataset_processors: [LinearInterpolation]

  - id: afolu_emissions
    name_en: Agriculture and forestry emissions
    name_de: Land- und Forstwirtschaft
    part_of: other_direct_emissions
    color: '#34b16f'
    historical_values: [[1990, 0.01253], [2020, 0.00843]]
    input_dataset_processors: [LinearInterpolation]

  - id: negative_emissions
    name_en: Negative emissions
    name_de: Negative Emissionen
    part_of: direct_emissions
    color: '#34B16F'
    historical_values: [[1990, 0], [2020, 0]]

  nodes:
  - id: population
    type: simple.AdditiveNode
    quantity: population
    unit: cap
    name_en: Inhabitants
    name_de: Einwohner/innen
    historical_values: [[1990, 359050], [2020, 439000]]
    forecast_values: [[2030, 492900], [2040, 520000], [2050, 540000]]
    input_dataset_processors: [LinearInterpolation]

  #
  # ------- ACTIONS --------
  #
  actions:
  - id: fossil_fuels_from_heating
    name_en: Replacement of fossil fuels in heating
    name_de: Ersatz fossiler Heizungen
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    description_en: If all 21 000 oil and gas heatings are replaced by heat pumps or
      district heat, direct building emissions are reduced by 1.6 tCO<sub>2</sub>eq/(inh.*a).
    description_de: Werden alle 21 000 Öl- und Gasheizungen mit Erdsonden oder
      einem Anschluss ans Fernwärmenetz ersetzt, reduzieren sich die direkten
      Emissionen von Gebäuden um 1.6 tCO<sub>2</sub>eq/(Einw.*a).
    output_nodes:
    - building_emissions
    forecast_values: [[2021, 0], [2040, -1.6]]
    input_dataset_processors:
      - type: FixedMultiplier
        params:
          multiplier: 0.775
    unit: t/inh/a

  - id: building_energy_retrofit
    name_en: Energetic retrofitting of buildings
    name_de: Energetische Gebäudesanierungen
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    output_nodes:
    - building_emissions
    forecast_values: [[2021, 0], [2040, -0.34]]
    input_dataset_processors:
      - type: FixedMultiplier
        params:
          multiplier: 0.775
    unit: t/inh/a

  - id: reduce_room_temperature
    name_en: Reduced room temperature
    name_de: Reduzierte Heiztemperatur
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    output_nodes:
    - building_emissions
    forecast_values: [[2021, 0], [2040, -0.1]]
    input_dataset_processors:
      - type: FixedMultiplier
        params:
          multiplier: 0.775
    unit: t/inh/a

  - id: modal_shift_to_public_transport
    name_en: Modal shift to public transport
    name_de: Förderung öV/Velo/Fussgänger
    description_en: If the traffic volume of public transport increases and car
      traffic sinks by 15%, direct mobility emissions are reduced by 0.05 tCO2eq/(inh.*a).
    description_de: Wenn die Verkehrsleistung des öV steigt und der Autoverkehr
      um 15% sinkt, reduzieren sich die direkten Emissionen der Mobilität um 0.05 tCO2eq/(Einw.*a).
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    output_nodes:
    - transportation_emissions
    forecast_values: [[2021, 0], [2040, -0.05]]
    input_dataset_processors:
      - type: FixedMultiplier
        params:
          multiplier: 0.833
    unit: t/inh/a

  - id: electric_mobility
    name_en: Electric mobility
    name_de: Elektromobilität
    description_en: If 80% of the petrol and diesel vehicles are replaced by
      electric vehicles, direct mobility emissions are reduced by 0.53 tCO2eq/(inh.*a).
    description_de: Wenn 80% der Diesel- und Benzinfahrzeuge durch Elektroautos
      ersetzt werden, reduzieren sich die direkten Emissionen der Mobiliät um 0.53 tCO2eq/(Einw.*a).
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    output_nodes:
    - transportation_emissions
    forecast_values: [[2021, 0], [2040, -0.53]]
    input_dataset_processors:
      - type: FixedMultiplier
        params:
          multiplier: 0.833
    unit: t/inh/a

  - id: electric_busses
    name_en: Electric busses
    name_de: Elektrobusse
    description_en: If the diesel busses of the municipal public transport
      company (VBZ) are replaced by battery busses, direct mobility emissions
      are reduced by 0.03 tCO2eq/(inh.*a).
    description_de: Wenn die Dieselbusse der VBZ durch Batteriebusse ersetzt
      werden, reduzieren sich die direkten Emissionen der Mobilität um
      0.03 tCO2eq/(Einw.*a).
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    output_nodes:
    - transportation_emissions
    forecast_values: [[2021, 0], [2040, -0.03]]
    input_dataset_processors:
      - type: FixedMultiplier
        params:
          multiplier: 0.833
    unit: t/inh/a

  - id: increase_carbon_sinks
    name_en: Increase carbon sinks
    name_de: Kohlenstoffsenken vergrössern
    type: simple.LinearCumulativeAdditiveAction
    quantity: emissions
    output_nodes:
    - negative_emissions
    forecast_values: [[2021, 0], [2030, -0.1], [2040, -0.4]]
    unit: t/inh/a

  pages:
  - id: home
    name_en: Net Zero 2040
    name_de: Netto-Null 2040
    path: /
    type: emission
    node: direct_emissions
    lead_title_en: Development version
    lead_title_de: Entwicklungsversion
    lead_paragraph_en: This is a test version of the City of Zürich's
      interactive scenario modeling platform for the Net Zero goal.
      All information on this website is to be considered incomplete and experimental.
    lead_paragraph_de: Dies ist eine Testversion der interaktiven Szenariomodellierungsplattform
      zu Zürichs Ziel Netto-Null 2040. Alle Informationen auf dieser Website sind als unvollständig
      und experimentell zu verstehen.

  scenarios:
  - id: baseline
    name_en: Baseline
    name_de: Basisszenario

  - id: default
    default: true
    name_en: Net Zero 2040
    name_de: Netto-Null 2040
    all_actions_enabled: true
